begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
select has_column('public','brand_assets','asset_type','brand assets expose typed visual metadata');
select has_column('public','brand_assets','quality_score','brand assets persist quality score');
select has_column('public','brand_profiles','primary_logo_asset_id','brand profile can reference primary logo');
select has_table('public','visual_template_profiles','visual template profile table exists');
select has_table('public','asset_usage_history','asset usage history table exists');
select has_table('public','visual_renders','visual render table exists');
select has_table('public','content_component_versions','component version audit table exists');
select has_table('public','visual_qa_issues','visual QA issue table exists');
select ok((select relrowsecurity from pg_class where oid='public.visual_template_profiles'::regclass),'template profiles have RLS');
select ok((select relrowsecurity from pg_class where oid='public.asset_usage_history'::regclass),'asset usage has RLS');
select ok((select relrowsecurity from pg_class where oid='public.visual_renders'::regclass),'visual renders have RLS');
select ok((select relrowsecurity from pg_class where oid='public.content_component_versions'::regclass),'component versions have RLS');
select ok((select relrowsecurity from pg_class where oid='public.visual_qa_issues'::regclass),'visual QA has RLS');
select ok(exists(select 1 from pg_constraint where conname='visual_renders_variant_tenant_fk'),'visual render variant FK is tenant-consistent');
select ok(exists(select 1 from pg_constraint where conname='visual_qa_render_tenant_fk'),'visual QA render FK is tenant-consistent');
select ok(exists(select 1 from pg_indexes where schemaname='public' and indexname='brand_assets_tenant_content_hash_unique'),'asset content hash is unique per tenant');
select is((select count(*)::bigint from storage.buckets where id in ('brand-assets','post-assets','tenant-documents') and public=false),3::bigint,'visual/document buckets remain private');
select ok(not has_table_privilege('authenticated','public.visual_renders','INSERT'),'authenticated client cannot forge visual renders');
select * from finish();
rollback;
