export const navigation = [
  ['Panoramica', '/app'],
  ['Onboarding', '/onboarding'],
  ['Brand Profile', '/app/brand'],
  ['Asset Library', '/app/assets'],
  ['Strategia', '/app/strategy'],
  ['Calendario', '/app/calendar'],
  ['Approvazioni', '/app/approvals'],
  ['Connessioni social', '/app/connections'],
  ['Analytics', '/app/analytics'],
  ['Notifiche', '/app/notifications'],
  ['Supporto', '/app/support'],
  ['Piano e quote', '/app/billing'],
  ['Impostazioni', '/app/settings'],
  ['Admin', '/admin'],
] as const;
