import assert from "node:assert/strict";
import fs from "node:fs";
const workflow=fs.readFileSync(".github/workflows/audit-viewer-runtime.yml","utf8");
const runtime=fs.readFileSync("tests/onboarding-runtime.mjs","utf8");
const controller=fs.readFileSync("tests/onboarding-runtime-qa-controller.ts","utf8");
const wrangler=fs.readFileSync("tests/wrangler.onboarding-runtime.jsonc","utf8");
assert.match(workflow,/^on:\s*\n\s+workflow_dispatch:\s*$/m); assert.doesNotMatch(workflow,/^\s+(push|pull_request):/m);
assert.match(workflow,/verify\/fase5-onboarding-runtime/); assert.match(workflow,/3c9697ae83a3422fafc2711658e7986b608349b1/);
assert.match(workflow,/wrangler versions upload/); assert.doesNotMatch(workflow,/\bwrangler (deploy|delete)\b/i); assert.match(workflow,/set -euo pipefail[\s\S]+node tests\/onboarding-runtime\.mjs \| tee/);
assert.match(workflow,/if: always\(\)/); assert.doesNotMatch(workflow,/actions\/upload-artifact/);
assert.match(runtime,/FASE_5A_ONBOARDING_RUNTIME: PASS/); assert.match(runtime,/ONBOARDING_IDEMPOTENCY_CONFLICT/); assert.match(runtime,/tenantIsolation:true/);
assert.match(controller,/cleanup-residue/); assert.match(controller,/onboarding-smoke-/); assert.match(controller,/metadata->>'phase'='FASE_5A'/);
assert.match(wrangler,/"preview_urls"\s*:\s*true/); assert.doesNotMatch(wrangler,/"routes"\s*:/);
console.log("FASE 5A onboarding runtime static safety: PASS");
