import assert from "node:assert/strict";
import fs from "node:fs";

const worker = fs.readFileSync("tests/same-origin-auth-feasibility-worker.mjs", "utf8");
const browser = fs.readFileSync("tests/same-origin-auth-feasibility-browser.mjs", "utf8");
const workflow = fs.readFileSync(".github/workflows/same-origin-auth-feasibility.yml", "utf8");
const config = fs.readFileSync("tests/wrangler.auth-feasibility.jsonc", "utf8");

assert.match(worker, /const AUTH_UPSTREAM = "https:\/\/ep-nameless-truth-a698bwer\.neonauth\.us-west-2\.aws\.neon\.tech\/neondb\/auth"/);
assert.match(worker, /const AUTH_PREFIX = "\/api\/auth"/);
assert.match(worker, /REQUEST_ALLOWLIST/);
assert.match(worker, /x-forwarded-host/);
assert.match(worker, /x-forwarded-proto/);
assert.match(worker, /cache-control", "no-store"/i);
assert.match(worker, /getSetCookie/);
assert.match(worker, /AUTH_PATH_NOT_ALLOWED/);
assert.match(worker, /METHOD_NOT_ALLOWED/);
assert.match(worker, /AUTH_REQUEST_TOO_LARGE/);
assert.doesNotMatch(worker, /request\.headers\.get\(["'](?:x-forwarded-host|x-forwarded-proto)["']\)/i);
assert.doesNotMatch(worker, /console\.(?:log|error)\([^\n]*(?:cookie|authorization|password|token)/i);
assert.doesNotMatch(worker, /jwt\.sign|createToken|session table|insert into neon_auth\.session/i);
assert.match(browser, /credentials: "include"/);
assert.match(browser, /headersArray\(\)/);
assert.match(browser, /context\.cookies\(base\)/);
assert.match(browser, /cookieReturnedToProxy/);
assert.match(browser, /sessionRecognized/);
assert.match(browser, /refreshPersistence/);
assert.match(browser, /nativeTokenFlow/);
assert.match(browser, /sensitiveFindings: 0/);
assert.doesNotMatch(browser, /console\.log\([^\n]*(?:password|nativeToken|\.value)/);
assert.match(workflow, /workflow_dispatch:/);
assert.doesNotMatch(workflow, /\n\s*(push|pull_request|schedule):/);
assert.match(workflow, /refs\/heads\/verify\/same-origin-auth-cookie-feasibility/);
assert.match(workflow, /wrangler versions upload/);
assert.match(workflow, /--preview-alias/);
assert.doesNotMatch(workflow, /wrangler (?:deploy|versions deploy)/);
assert.match(workflow, /if: always\(\)/);
assert.match(config, /"main": "\.\/same-origin-auth-feasibility-worker\.mjs"/);
console.log("SAME_ORIGIN_AUTH_FEASIBILITY_STATIC: PASS");
