import assert from "node:assert/strict";
import fs from "node:fs";

const worker = fs.readFileSync("tests/same-origin-auth-feasibility-worker.mjs", "utf8");
const browser = fs.readFileSync("tests/same-origin-auth-feasibility-browser.mjs", "utf8");
const workflow = fs.readFileSync(".github/workflows/audit-viewer-runtime.yml", "utf8");
const config = fs.readFileSync("tests/wrangler.auth-feasibility.jsonc", "utf8");

assert.match(worker, /const AUTH_UPSTREAM = "https:\/\/ep-nameless-truth-a698bwer\.neonauth\.us-west-2\.aws\.neon\.tech\/neondb\/auth"/);
assert.match(worker, /const APP_ORIGIN = "https:\/\/autoposter\.02alessandrocaruso\.workers\.dev"/);
assert.match(worker, /const AUTH_PREFIX = "\/api\/auth"/);
assert.match(worker, /REQUEST_ALLOWLIST/);
assert.match(worker, /FORWARDED_FROM_CLIENT/);
assert.match(worker, /INVALID_HOSTNAME/);
assert.doesNotMatch(worker, /headers\.set\("x-forwarded-(?:host|proto)"/);
assert.match(worker, /request\.headers\.get\("origin"\) !== APP_ORIGIN/);
assert.match(worker, /ORIGIN_NOT_ALLOWED/);
assert.match(worker, /cache-control", "no-store"/i);
assert.match(worker, /getSetCookie/);
assert.match(worker, /AUTH_PATH_NOT_ALLOWED/);
assert.match(worker, /METHOD_NOT_ALLOWED/);
assert.match(worker, /AUTH_REQUEST_TOO_LARGE/);
assert.doesNotMatch(worker, /request\.headers\.get\(["'](?:x-forwarded-host|x-forwarded-proto)["']\)/i);
assert.doesNotMatch(worker, /console\.(?:log|error)\([^\n]*(?:cookie|authorization|password|token)/i);
assert.doesNotMatch(worker, /jwt\.sign|createToken|session table|insert into neon_auth\.session/i);

assert.match(browser, /const appOrigin = "https:\/\/autoposter\.02alessandrocaruso\.workers\.dev"/);
assert.match(browser, /context\.route\(`\$\{previewBase\}\/api\/auth\/\*\*`/);
assert.match(browser, /headers\.origin = appOrigin/);
assert.match(browser, /headers\.referer = `\$\{appOrigin\}\//);
assert.match(browser, /route\.continue\(\{ headers \}\)/);
assert.doesNotMatch(browser, /route\.fetch\(/);
assert.doesNotMatch(browser, /route\.fulfill\(/);
assert.match(browser, /credentials: "include"/);
assert.match(browser, /headersArray\(\)/);
assert.match(browser, /context\.cookies\(previewBase\)/);
assert.match(browser, /origin: "https:\/\/evil\.invalid"/);
assert.match(browser, /foreign\.status, 403/);
assert.match(browser, /directNeonBrowserRequest/);
assert.match(browser, /cookieReturnedToProxy/);
assert.match(browser, /sessionRecognized/);
assert.match(browser, /refreshPersistence/);
assert.match(browser, /nativeTokenFlow/);
assert.match(browser, /browserTransport: "REAL_PREVIEW_NETWORK"/);
assert.match(browser, /trustedOriginSimulation: "CANONICAL_APP_ORIGIN"/);
assert.match(browser, /sensitiveFindings: 0/);
assert.doesNotMatch(browser, /console\.log\([^\n]*(?:password|nativeToken|\.value)/);

assert.match(workflow, /name: Audit Viewer Authenticated Runtime/);
assert.match(workflow, /workflow_dispatch:/);
assert.doesNotMatch(workflow, /\n\s*(push|pull_request|schedule):/);
assert.match(workflow, /refs\/heads\/verify\/same-origin-auth-cookie-feasibility/);
assert.match(workflow, /same-origin-auth-cookie-feasibility/);
assert.match(workflow, /wrangler versions upload/);
assert.match(workflow, /wrangler\.auth-feasibility\.jsonc/);
assert.match(workflow, /--preview-alias/);
assert.doesNotMatch(workflow, /wrangler (?:deploy|versions deploy)/);
assert.match(workflow, /if: always\(\)/);
assert.match(config, /"main": "\.\/same-origin-auth-feasibility-worker\.mjs"/);
console.log("SAME_ORIGIN_AUTH_FEASIBILITY_STATIC: PASS");
