import { useEffect, useMemo, useState } from 'react';
import { Badge, Card, EmptyState } from './ui';
import { useLocalE2E } from '../services/local-e2e';
import './media-picker.css';

type PickerAsset={id:string;asset_type:string;original_filename:string;description:string|null;tags:string[];suitable_topics:string[];quality_score:number|null;is_preferred:boolean;status:string;usage_count:number;last_used_at:string|null;thumbnail_small_url:string|null;thumbnail_medium_url:string|null;preview_url:string|null;};

export function MediaPicker({variantId,topic,currentAssetId,onSelected,onClose}:{variantId:string;topic:string;currentAssetId?:string|null;onSelected?:(result:unknown)=>void;onClose?:()=>void}){
  const local=useLocalE2E();const [assets,setAssets]=useState<PickerAsset[]>([]);const [search,setSearch]=useState('');const [type,setType]=useState('');const [selected,setSelected]=useState(currentAssetId??'');const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);
  const load=async()=>{if(!local.tenantId)return;const params=new URLSearchParams({status:'ACTIVE'});if(search)params.set('search',search);if(type)params.set('type',type);setAssets(await local.api<PickerAsset[]>(`/tenants/${local.tenantId}/assets?${params}`));};
  useEffect(()=>{void load()},[local.tenantId]);
  const normalizedTopic=topic.toLowerCase();
  const ranked=useMemo(()=>[...assets].filter((asset)=>asset.status==='ACTIVE').sort((a,b)=>score(b)-score(a)),[assets,normalizedTopic]);
  const compatible=ranked.filter((asset)=>asset.suitable_topics?.some((item)=>normalizedTopic.includes(item.toLowerCase())||item.toLowerCase().includes(normalizedTopic)));
  const preferred=ranked.filter((asset)=>asset.is_preferred);
  const recent=ranked.filter((asset)=>asset.last_used_at).sort((a,b)=>new Date(b.last_used_at??0).getTime()-new Date(a.last_used_at??0).getTime()).slice(0,8);
  function score(asset:PickerAsset){return(asset.is_preferred?30:0)+(asset.suitable_topics?.some((item)=>normalizedTopic.includes(item.toLowerCase())||item.toLowerCase().includes(normalizedTopic))?25:0)+Number(asset.quality_score??0)*20-Math.min(asset.usage_count??0,10);}
  const upload=async(file:File)=>{if(!local.tenantId)return;setBusy(true);try{const base64=await fileToBase64(file);const result=await local.api<{asset:PickerAsset}>(`/tenants/${local.tenantId}/assets`,{method:'POST',body:JSON.stringify({filename:file.name,mimeType:file.type,dataBase64:base64})});await load();setSelected(result.asset.id);setMessage('Nuovo asset caricato e selezionato.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const confirm=async()=>{if(!local.tenantId||!selected)return;setBusy(true);try{const result=await local.api(`/tenants/${local.tenantId}/variants/${variantId}/visual`,{method:'POST',body:JSON.stringify({assetId:selected})});setMessage('Foto sostituita: solo visual selection/render/QA/versione sono stati aggiornati.');onSelected?.(result)}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
  const assetTypes=[...new Set(assets.map((asset)=>asset.asset_type))].sort();
  return <Card className="media-picker" data-testid="media-picker"><div className="row-between"><div><span className="eyebrow">Asset Library</span><h3>Scegli una foto specifica</h3></div>{onClose&&<button type="button" data-testid="media-picker-close" className="ghost-button" onClick={onClose}>Chiudi</button>}</div><div className="media-picker-toolbar"><input data-testid="media-picker-search" placeholder="Cerca foto, tag o descrizione" value={search} onChange={(e)=>setSearch(e.target.value)}/><select aria-label="Filtra asset picker" value={type} onChange={(e)=>setType(e.target.value)}><option value="">Tutti i tipi</option>{assetTypes.map((item)=><option key={item}>{item}</option>)}</select><button type="button" className="button secondary" onClick={()=>void load()}>Filtra</button><label className="button secondary file-button">Carica nuovo<input data-testid="media-picker-upload" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(e)=>{const file=e.target.files?.[0];if(file)void upload(file);e.currentTarget.value=''}}/></label></div>{message&&<p role="status">{message}</p>}<PickerGroup title="Compatibili col topic" assets={compatible} selected={selected} setSelected={setSelected}/><PickerGroup title="Preferiti" assets={preferred.filter((item)=>!compatible.includes(item))} selected={selected} setSelected={setSelected}/><PickerGroup title="Recenti" assets={recent.filter((item)=>!compatible.includes(item)&&!preferred.includes(item))} selected={selected} setSelected={setSelected}/><PickerGroup title="Tutta la libreria" assets={ranked.filter((item)=>!compatible.includes(item)&&!preferred.includes(item)&&!recent.includes(item))} selected={selected} setSelected={setSelected}/>{ranked.length===0&&<EmptyState title="Nessun asset attivo" body="Carica una fotografia: gli asset BLOCKED e ARCHIVED non vengono proposti."/>}<div className="media-picker-footer"><small>Asset selezionato: {selected||'nessuno'} · hook/caption/CTA/hashtag non verranno rigenerati.</small><button type="button" data-testid="media-picker-confirm" className="button" disabled={!selected||busy} onClick={()=>void confirm()}>{busy?'Elaborazione…':'Conferma selezione'}</button></div></Card>;
}

function PickerGroup({title,assets,selected,setSelected}:{title:string;assets:PickerAsset[];selected:string;setSelected:(id:string)=>void}){if(!assets.length)return null;return <section className="media-picker-group"><div className="row-between"><strong>{title}</strong><Badge>{assets.length}</Badge></div><div className="media-picker-grid">{assets.map((asset)=><button type="button" data-testid={`media-picker-asset-${asset.id}`} key={asset.id} className={`media-picker-item ${selected===asset.id?'selected':''}`} onClick={()=>setSelected(asset.id)}>{asset.thumbnail_small_url??asset.preview_url?<img loading="lazy" src={asset.thumbnail_small_url??asset.preview_url??''} alt={asset.description??asset.original_filename}/>:<span className="media-picker-placeholder">{asset.asset_type}</span>}<span><strong>{asset.original_filename}</strong><small>{asset.asset_type} · {Math.round(Number(asset.quality_score??0)*100)}%</small></span>{asset.is_preferred&&<Badge>Preferito</Badge>}</button>)}</div></section>}

const fileToBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.readAsDataURL(file)});
