import { expect, test, type APIRequestContext } from '@playwright/test';

const API=process.env.E2E_API_URL??'http://127.0.0.1:8787';
const WEB=process.env.E2E_WEB_URL??'http://127.0.0.1:5173';
const password='ProviderReadiness-password-123!';
const authHeaders=(token:string)=>({authorization:`Bearer ${token}`,'content-type':'application/json'});

async function requestJson<T>(request:APIRequestContext,token:string|null,path:string,method='GET',data?:unknown):Promise<T>{const response=await request.fetch(`${API}${path}`,{method,headers:token?authHeaders(token):{'content-type':'application/json'},data});const body=await response.json().catch(()=>({}));if(!response.ok())throw new Error(`${response.status()} ${path}: ${JSON.stringify(body)}`);return body as T;}
async function setup(request:APIRequestContext,label:string){const email=`provider-${Date.now()}-${Math.random().toString(16).slice(2)}@example.test`;const session=await requestJson<any>(request,null,'/auth/register','POST',{email,password,name:label});const slug=`${label}-${Date.now()}`.toLowerCase().replace(/[^a-z0-9]+/g,'-');const tenant=await requestJson<{tenantId:string}>(request,session.access_token,'/tenants','POST',{name:label,slug});return{token:session.access_token as string,tenantId:tenant.tenantId};}
const publishPayload=(platform:string,accountId:string)=>({platform,accountId,format:platform==='google_business_profile'?'local_post':platform==='instagram'?'image':'text',text:'Provider readiness E2E',media:platform==='instagram'?[{mimeType:'image/jpeg',url:'https://fixture.invalid/a.jpg'}]:[],idempotencyKey:`provider-e2e-${accountId.slice(0,12)}`,correlationId:`corr-${Date.now()}-${Math.random().toString(16).slice(2)}`});

test.describe('provider readiness E2E',()=>{
  test('OAuth fixtures discover multiple accounts, health, validation, dry-run, publish, analytics, reconnect and revoke',async({request})=>{
    const user=await setup(request,'Provider Owner');
    for(const provider of ['meta','linkedin','google_business_profile'])await requestJson(request,user.token,`/tenants/${user.tenantId}/providers/${provider}/connect-mock`,'POST',{});
    const connections=await requestJson<any[]>(request,user.token,`/tenants/${user.tenantId}/provider-connections`);
    expect(connections.length).toBe(3);
    const meta=connections.find((item)=>item.provider==='meta');expect(meta).toBeTruthy();expect(meta.accounts.some((item:any)=>item.platform==='facebook')).toBe(true);expect(meta.accounts.some((item:any)=>item.platform==='instagram')).toBe(true);
    const linkedIn=connections.find((item)=>item.provider==='linkedin');expect(linkedIn.accounts.length).toBeGreaterThanOrEqual(2);
    const gbp=connections.find((item)=>item.provider==='google_business_profile');expect(gbp.accounts.length).toBeGreaterThanOrEqual(2);
    for(const connection of connections){expect((await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-connections/${connection.id}/health`)).status).toBe('CONNECTED');const account=connection.accounts.find((item:any)=>item.is_selected||item.selected)??connection.accounts[0];const platform=String(account.platform);const payload=publishPayload(platform,account.id);expect((await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-accounts/${account.id}/validate`,'POST',payload)).valid).toBe(true);const dry=await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-accounts/${account.id}/dry-run`,'POST',payload);expect(dry.mode).toBe('DRY_RUN');expect(dry.wouldPublish).toBe(true);const published=await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-accounts/${account.id}/mock-publish`,'POST',payload);expect(published.externalPostId).toBeTruthy();expect((await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-accounts/${account.id}/analytics?externalPostId=${encodeURIComponent(published.externalPostId)}`)).availableMetricKeys.length).toBeGreaterThan(0);}
    await requestJson(request,user.token,`/tenants/${user.tenantId}/provider-connections/${linkedIn.id}/simulate`,'POST',{scenario:'expired'});expect((await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-connections/${linkedIn.id}/health`)).status).toBe('REAUTH_REQUIRED');const reconnect=await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-connections/${linkedIn.id}/reconnect`,'POST',{});expect(reconnect.connectionId).toBe(linkedIn.id);expect(reconnect.status).toBe('CONNECTED');const revoke=await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-connections/${gbp.id}/revoke`,'POST',{});expect(revoke.historyPreserved).toBe(true);expect((await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-connections/${gbp.id}/health`)).status).toBe('DISCONNECTED');
    const audit=await requestJson<any[]>(request,user.token,`/tenants/${user.tenantId}/provider-audit`);expect(audit.some((item)=>item.action==='publish_mock')).toBe(true);expect(JSON.stringify(audit)).not.toContain('mock-access-');expect(JSON.stringify(audit)).not.toContain('mock-refresh-');
  });

  test('provider validator blocks known unsupported formats before sending',async({request})=>{const user=await setup(request,'Validator Owner');await requestJson(request,user.token,`/tenants/${user.tenantId}/providers/linkedin/connect-mock`,'POST',{});await requestJson(request,user.token,`/tenants/${user.tenantId}/providers/google_business_profile/connect-mock`,'POST',{});const connections=await requestJson<any[]>(request,user.token,`/tenants/${user.tenantId}/provider-connections`);const li=connections.find((item)=>item.provider==='linkedin').accounts[0];const badLi={...publishPayload('linkedin',li.id),format:'carousel'};const liValidation=await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-accounts/${li.id}/validate`,'POST',badLi);expect(liValidation.valid).toBe(false);expect(liValidation.issues.some((item:any)=>item.code==='LINKEDIN_ORGANIC_CAROUSEL_UNSUPPORTED')).toBe(true);const gbp=connections.find((item)=>item.provider==='google_business_profile').accounts[0];const badGbp={...publishPayload('google_business_profile',gbp.id),format:'product'};const gbpValidation=await requestJson<any>(request,user.token,`/tenants/${user.tenantId}/provider-accounts/${gbp.id}/validate`,'POST',badGbp);expect(gbpValidation.valid).toBe(false);expect(gbpValidation.issues.some((item:any)=>item.code==='GBP_PRODUCT_POST_UNSUPPORTED')).toBe(true);});

  test('browser connects fixtures, shows health, uses admin dry-run and remains usable on mobile',async({page,request})=>{const user=await setup(request,'Provider Browser Owner');await page.addInitScript(({token,tenantId})=>{localStorage.setItem('socialpilot.local.token',token);localStorage.setItem('socialpilot.local.tenant',tenantId);},{token:user.token,tenantId:user.tenantId});const errors:string[]=[];page.on('console',(msg)=>{if(msg.type()==='error')errors.push(msg.text())});page.on('pageerror',(error)=>errors.push(error.message));await page.goto(`${WEB}/app/connections`);await expect(page.getByText('Social Connections & Health')).toBeVisible();await page.getByTestId('connect-meta').click();await expect(page.getByText('Forno Vesuvio Milano')).toBeVisible();await page.getByTestId('connect-linkedin').click();await expect(page.getByText('SocialPilot Demo Company')).toBeVisible();await page.getByTestId('connect-google_business_profile').click();await expect(page.getByText('Forno Vesuvio · Milano Centro')).toBeVisible();await expect(page.getByText('CONNECTED').first()).toBeVisible();await page.goto(`${WEB}/admin/providers`);if(await page.getByTestId('provider-console-claim-admin').isVisible().catch(()=>false))await page.getByTestId('provider-console-claim-admin').click();await expect(page.getByTestId('provider-console-account')).toBeVisible();await page.getByTestId('provider-console-dry-run').click();await expect(page.getByTestId('provider-console-output')).toContainText('DRY_RUN');await page.setViewportSize({width:390,height:844});await page.goto(`${WEB}/app/connections`);await expect(page.getByText('Social Connections & Health')).toBeVisible();expect(errors).toEqual([]);});
});
