import { createHmac } from 'node:crypto';
import { expect,test,type APIRequestContext } from '@playwright/test';
const API=process.env.E2E_API_URL??'http://127.0.0.1:8787';
const password='WebhookE2E-password-123!';
const secret=process.env.LOCAL_PROVIDER_WEBHOOK_SECRET??'local-provider-webhook-secret';
const authHeaders=(token:string)=>({authorization:`Bearer ${token}`,'content-type':'application/json'});
async function json<T>(request:APIRequestContext,token:string|null,path:string,method='GET',data?:unknown):Promise<T>{const response=await request.fetch(`${API}${path}`,{method,headers:token?authHeaders(token):{'content-type':'application/json'},data});const body=await response.json().catch(()=>({}));if(!response.ok())throw new Error(`${response.status()} ${path}: ${JSON.stringify(body)}`);return body as T;}
async function setup(request:APIRequestContext,label:string){const email=`webhook-${Date.now()}-${Math.random().toString(16).slice(2)}@example.test`;const session=await json<any>(request,null,'/auth/register','POST',{email,password,name:label});const tenant=await json<{tenantId:string}>(request,session.access_token,'/tenants','POST',{name:label,slug:`webhook-${Date.now()}-${Math.random().toString(16).slice(2,7)}`});await json(request,session.access_token,`/tenants/${tenant.tenantId}/providers/meta/connect-mock`,'POST',{});const connections=await json<any[]>(request,session.access_token,`/tenants/${tenant.tenantId}/provider-connections`);const account=connections[0].accounts[0];return{token:session.access_token as string,tenantId:tenant.tenantId,accountId:account.id};}
const sign=(raw:string,timestamp:number)=>`sha256=${createHmac('sha256',secret).update(`${timestamp}.${raw}`).digest('hex')}`;

test('webhook core verifies signature, deduplicates and rejects wrong tenant mapping',async({request})=>{
  const a=await setup(request,'Webhook Tenant A'),b=await setup(request,'Webhook Tenant B');const raw=JSON.stringify({type:'fixture.publish',accountId:a.accountId});const timestamp=Date.now();const headers={'content-type':'application/json','x-provider-timestamp':String(timestamp),'x-provider-signature':sign(raw,timestamp),'x-event-id':`evt-${timestamp}`,'x-event-type':'fixture.publish','x-tenant-id':a.tenantId,'x-account-id':a.accountId};
  const first=await request.post(`${API}/webhooks/mock/facebook`,{headers,data:raw});expect(first.status()).toBe(200);expect((await first.json()).status).toBe('PROCESSED');const duplicate=await request.post(`${API}/webhooks/mock/facebook`,{headers,data:raw});expect(duplicate.status()).toBe(200);expect((await duplicate.json()).status).toBe('IGNORED_DUPLICATE');
  const forged=await request.post(`${API}/webhooks/mock/facebook`,{headers:{...headers,'x-event-id':`forged-${timestamp}`,'x-provider-signature':'sha256=forged'},data:raw});expect(forged.status()).toBe(401);
  const old=timestamp-10*60_000;const stale=await request.post(`${API}/webhooks/mock/facebook`,{headers:{...headers,'x-event-id':`stale-${timestamp}`,'x-provider-timestamp':String(old),'x-provider-signature':sign(raw,old)},data:raw});expect(stale.status()).toBe(401);
  const wrongTenant=await request.post(`${API}/webhooks/mock/facebook`,{headers:{...headers,'x-event-id':`wrong-${timestamp}`,'x-tenant-id':b.tenantId},data:raw});expect(wrongTenant.status()).toBe(400);expect((await wrongTenant.json()).error).toContain('WEBHOOK_TENANT_MAPPING_INVALID');
  const malformedRaw='not-json';const malformedTs=Date.now();const malformed=await request.post(`${API}/webhooks/mock/facebook`,{headers:{'content-type':'application/json','x-provider-timestamp':String(malformedTs),'x-provider-signature':sign(malformedRaw,malformedTs),'x-event-id':`malformed-${malformedTs}`,'x-event-type':'fixture.publish'},data:malformedRaw});expect(malformed.status()).toBe(400);expect((await malformed.json()).error).toContain('WEBHOOK_MALFORMED_PAYLOAD');
});
