import { expect, test, type APIRequestContext, type Page } from '@playwright/test';
const API=process.env.E2E_API_URL??'http://127.0.0.1:8787';
const password='LocalE2E-password-123!';
async function requestJson<T>(request:APIRequestContext,token:string|null,path:string,method='GET',data?:unknown):Promise<T>{const response=await request.fetch(`${API}${path}`,{method,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},...(data===undefined?{}:{data})});const body=await response.json().catch(()=>({}));if(!response.ok())throw new Error(`${response.status()} ${path}: ${JSON.stringify(body)}`);return body as T}
async function setup(request:APIRequestContext){const email=`visual-browser-${Date.now()}@example.test`;const session=await requestJson<any>(request,null,'/auth/register','POST',{email,password,name:'Visual Browser Owner'});const token=session.access_token as string;const {tenantId}=await requestJson<{tenantId:string}>(request,token,'/tenants','POST',{name:'Browser Visual Pizza',slug:`browser-visual-${Date.now()}`});await requestJson(request,token,`/tenants/${tenantId}/onboarding`,'PATCH',{business:{name:'Browser Visual Pizza',website:`${API}/fixture-site/pizza-visual-browser/`,industry:'Pizzeria',subIndustry:'Napoletana',location:'Milano',language:'it',serviceArea:'Milano',services:'pizza margherita, impasto, forno',differentiator:'artigianalità'},current_step:'goals'});await requestJson(request,token,`/tenants/${tenantId}/onboarding`,'PATCH',{goals:['lead','notorietà'],current_step:'target'});await requestJson(request,token,`/tenants/${tenantId}/onboarding`,'PATCH',{target:{manual:['famiglie locali'],suggestions:[]},current_step:'brand'});await requestJson(request,token,`/tenants/${tenantId}/scan`,'POST',{});await requestJson(request,token,`/tenants/${tenantId}/brand/status`,'POST',{status:'confirmed'});await requestJson(request,token,`/tenants/${tenantId}/social`,'POST',{platforms:['instagram'],publishingModes:{instagram:'manual'}});await requestJson(request,token,`/tenants/${tenantId}/onboarding`,'PATCH',{frequency:{postsPerWeek:2,days:[1,3],times:['10:00']},publishing_modes:{instagram:'manual'},current_step:'summary'});await requestJson(request,token,`/tenants/${tenantId}/onboarding/complete`,'POST',{});return{token,tenantId}}
async function setSession(page:Page,token:string,tenantId:string){await page.goto('/');await page.evaluate(({token,tenantId})=>{localStorage.setItem('socialpilot.local.token',token);localStorage.setItem('socialpilot.local.tenant',tenantId)},{token,tenantId})}
const svgBuffer=(label:string,color:string)=>Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="900"><rect width="1200" height="900" fill="${color}"/><text x="80" y="160" fill="#fff" font-size="72">${label}</text></svg>`);

test('browser Asset Library and Approval Center use persisted visual data',async({page,request})=>{const errors:string[]=[];page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});page.on('pageerror',error=>errors.push(error.message));const {token,tenantId}=await setup(request);await setSession(page,token,tenantId);await page.goto('/app/assets');await expect(page.getByRole('heading',{name:'Asset Library'})).toBeVisible();const upload=page.getByTestId('asset-upload');await upload.setInputFiles({name:'logo-browser.svg',mimeType:'image/svg+xml',buffer:svgBuffer('LOGO','#111827')});await expect(page.getByText('logo-browser.svg')).toBeVisible();await upload.setInputFiles({name:'pizza-margherita-food.svg',mimeType:'image/svg+xml',buffer:svgBuffer('PIZZA','#991b1b')});await expect(page.getByText('pizza-margherita-food.svg')).toBeVisible();await page.getByTestId('asset-search').fill('pizza');await page.getByRole('button',{name:'Filtra'}).click();await expect(page.getByText('pizza-margherita-food.svg')).toBeVisible();await requestJson(request,token,`/tenants/${tenantId}/calendar`,'POST',{weeks:1});await requestJson(request,token,`/tenants/${tenantId}/posts/generate-all`,'POST',{limit:10});await page.goto('/approvals');await expect(page.getByRole('heading',{name:'Approval Center'})).toBeVisible();await expect(page.locator('.approval-preview img').first()).toBeVisible({timeout:30_000});await expect(page.getByRole('button',{name:'CAMBIA GRAFICA'}).first()).toBeVisible();await expect(page.getByRole('button',{name:'CAMBIA FOTO'}).first()).toBeVisible();await page.getByRole('button',{name:'CAMBIA GRAFICA'}).first().click();await expect(page.getByText('Operazione salvata nel database locale.')).toBeVisible();await page.setViewportSize({width:390,height:844});await page.goto('/app/assets');expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(2);expect(errors,errors.join('\n')).toEqual([])});
