import { afterAll,beforeAll,describe,expect,it } from 'vitest';
import { createClient,type SupabaseClient } from '@supabase/supabase-js';
const url=process.env.TEST_SUPABASE_URL,publishableKey=process.env.TEST_SUPABASE_PUBLISHABLE_KEY,serviceRoleKey=process.env.TEST_SUPABASE_SERVICE_ROLE_KEY;
const suite=url&&publishableKey&&serviceRoleKey?describe:describe.skip;

suite('provider readiness tenant isolation',()=>{
  const run=crypto.randomUUID(),password=`Provider-${run}!Aa9`;let admin:SupabaseClient,clientA:SupabaseClient,clientB:SupabaseClient,userA='',userB='',tenantA='',tenantB='',connectionA='',connectionB='',accountA='',accountB='',assetA='';
  beforeAll(async()=>{
    admin=createClient(url!,serviceRoleKey!,{auth:{persistSession:false,autoRefreshToken:false}});
    const emailA=`provider-a-${run}@example.test`,emailB=`provider-b-${run}@example.test`;
    const [a,b]=await Promise.all([admin.auth.admin.createUser({email:emailA,password,email_confirm:true}),admin.auth.admin.createUser({email:emailB,password,email_confirm:true})]);if(a.error)throw a.error;if(b.error)throw b.error;userA=a.data.user.id;userB=b.data.user.id;
    clientA=createClient(url!,publishableKey!,{auth:{persistSession:false,autoRefreshToken:false}});clientB=createClient(url!,publishableKey!,{auth:{persistSession:false,autoRefreshToken:false}});
    const [la,lb]=await Promise.all([clientA.auth.signInWithPassword({email:emailA,password}),clientB.auth.signInWithPassword({email:emailB,password})]);if(la.error)throw la.error;if(lb.error)throw lb.error;
    const [ta,tb]=await Promise.all([clientA.rpc('create_tenant',{p_name:'Provider A',p_slug:`provider-a-${run}`}),clientB.rpc('create_tenant',{p_name:'Provider B',p_slug:`provider-b-${run}`})]);if(ta.error)throw ta.error;if(tb.error)throw tb.error;tenantA=ta.data as string;tenantB=tb.data as string;
    const connections=await admin.from('social_connections').insert([{tenant_id:tenantA,platform:'facebook',connection_status:'connected',approval_mode:'manual',provider_subject_id:`a-${run}`},{tenant_id:tenantB,platform:'facebook',connection_status:'connected',approval_mode:'manual',provider_subject_id:`b-${run}`}]).select('id,tenant_id');if(connections.error)throw connections.error;connectionA=connections.data.find(x=>x.tenant_id===tenantA)!.id;connectionB=connections.data.find(x=>x.tenant_id===tenantB)!.id;
    const accounts=await admin.from('social_accounts').insert([{tenant_id:tenantA,connection_id:connectionA,platform:'facebook',external_account_id:`page-a-${run}`,display_name:'Page A',account_type:'page'},{tenant_id:tenantB,connection_id:connectionB,platform:'facebook',external_account_id:`page-b-${run}`,display_name:'Page B',account_type:'page'}]).select('id,tenant_id');if(accounts.error)throw accounts.error;accountA=accounts.data.find(x=>x.tenant_id===tenantA)!.id;accountB=accounts.data.find(x=>x.tenant_id===tenantB)!.id;
    const asset=await admin.from('brand_assets').insert({tenant_id:tenantA,kind:'document',storage_bucket:'tenant-documents',storage_path:`${tenantA}/docs/provider.txt`,original_filename:'provider.txt',mime_type:'text/plain',content_hash:`provider-doc-${run}`,asset_type:'document',status:'ACTIVE'}).select('id').single();if(asset.error)throw asset.error;assetA=asset.data.id;
    const ingestion=await admin.from('document_ingestions').insert({tenant_id:tenantA,asset_id:assetA,status:'INDEXED',provider_key:'mock-local',extracted_text:'FAQ fixture',chunk_count:1}).select('id').single();if(ingestion.error)throw ingestion.error;
    const source=await admin.from('knowledge_sources').insert({tenant_id:tenantA,source_type:'DOCUMENT',source_ref:assetA,source_entity_id:assetA,confidence:.9}).select('id').single();if(source.error)throw source.error;
    await admin.from('knowledge_facts').insert({tenant_id:tenantA,source_id:source.data.id,fact_key:'faq.test',fact_value:{value:'tenant-a-only'},confidence:.9});
    await admin.from('provider_audit_events').insert([{tenant_id:tenantA,actor_user_id:userA,provider:'facebook',connection_id:connectionA,account_id:accountA,action:'connect',outcome:'success'},{tenant_id:tenantB,actor_user_id:userB,provider:'facebook',connection_id:connectionB,account_id:accountB,action:'connect',outcome:'success'}]);
    await admin.from('provider_webhook_events').insert([{tenant_id:tenantA,connection_id:connectionA,account_id:accountA,provider:'facebook',event_type:'fixture',external_id:`evt-a-${run}`,payload_hash:`hash-a-${run}`,signature_status:'verified',processing_status:'PROCESSED'},{tenant_id:tenantB,connection_id:connectionB,account_id:accountB,provider:'facebook',event_type:'fixture',external_id:`evt-b-${run}`,payload_hash:`hash-b-${run}`,signature_status:'verified',processing_status:'PROCESSED'}]);
  });
  afterAll(async()=>{if(tenantA||tenantB)await admin.from('tenants').delete().in('id',[tenantA,tenantB].filter(Boolean));await Promise.all([userA?admin.auth.admin.deleteUser(userA):Promise.resolve(),userB?admin.auth.admin.deleteUser(userB):Promise.resolve()]);});

  it('keeps provider audit and webhook ledgers tenant-scoped',async()=>{const [auditA,auditB,webhookA,webhookB]=await Promise.all([clientA.from('provider_audit_events').select('tenant_id'),clientB.from('provider_audit_events').select('tenant_id'),clientA.from('provider_webhook_events').select('tenant_id'),clientB.from('provider_webhook_events').select('tenant_id')]);expect(auditA.error).toBeNull();expect(auditB.error).toBeNull();expect(webhookA.error).toBeNull();expect(webhookB.error).toBeNull();expect(auditA.data?.every(x=>x.tenant_id===tenantA)).toBe(true);expect(auditB.data?.every(x=>x.tenant_id===tenantB)).toBe(true);expect(webhookA.data?.every(x=>x.tenant_id===tenantA)).toBe(true);expect(webhookB.data?.every(x=>x.tenant_id===tenantB)).toBe(true);});
  it('keeps document ingestion and knowledge provenance tenant-scoped',async()=>{const own=await clientA.from('document_ingestions').select('tenant_id,asset_id').eq('asset_id',assetA);expect(own.error).toBeNull();expect(own.data).toEqual([{tenant_id:tenantA,asset_id:assetA}]);const hidden=await clientB.from('document_ingestions').select('tenant_id,asset_id').eq('asset_id',assetA);expect(hidden.error).toBeNull();expect(hidden.data).toEqual([]);const facts=await clientB.from('knowledge_facts').select('fact_value').eq('tenant_id',tenantA);expect(facts.error).toBeNull();expect(facts.data).toEqual([]);});
  it('does not expose OAuth state or integration credentials through authenticated role',async()=>{const oauth=await clientA.schema('app_private').from('oauth_states').select('*');expect(oauth.error).not.toBeNull();const credentials=await clientA.schema('app_private').from('integration_credentials').select('*');expect(credentials.error).not.toBeNull();});
  it('prevents client writes to server-only provider evidence tables',async()=>{const audit=await clientA.from('provider_audit_events').insert({tenant_id:tenantA,provider:'facebook',action:'forge',outcome:'success'});expect(audit.error).not.toBeNull();const webhook=await clientA.from('provider_webhook_events').insert({tenant_id:tenantA,provider:'facebook',event_type:'forge',payload_hash:`forge-${run}`,signature_status:'verified',processing_status:'PROCESSED'});expect(webhook.error).not.toBeNull();});
  it('rejects cross-tenant provider account references at relational boundary',async()=>{const cross=await admin.from('provider_permission_grants').insert({tenant_id:tenantA,connection_id:connectionA,account_id:accountB,provider:'facebook',scope:'pages_manage_posts',feature_key:'publish_post',requirement:'required',status:'granted'});expect(cross.error).not.toBeNull();});
});
