import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
const url=process.env.TEST_SUPABASE_URL,publishableKey=process.env.TEST_SUPABASE_PUBLISHABLE_KEY,serviceRoleKey=process.env.TEST_SUPABASE_SERVICE_ROLE_KEY;
const suite=url&&publishableKey&&serviceRoleKey?describe:describe.skip;
suite('visual asset and storage tenant isolation',()=>{
 const run=crypto.randomUUID(),password=`Asset-${run}!Aa9`;let admin:SupabaseClient,clientA:SupabaseClient,clientB:SupabaseClient,userA='',userB='',tenantA='',tenantB='',assetA='',assetB='';
 beforeAll(async()=>{admin=createClient(url!,serviceRoleKey!,{auth:{persistSession:false,autoRefreshToken:false}});const emailA=`asset-a-${run}@example.test`,emailB=`asset-b-${run}@example.test`;const [a,b]=await Promise.all([admin.auth.admin.createUser({email:emailA,password,email_confirm:true}),admin.auth.admin.createUser({email:emailB,password,email_confirm:true})]);if(a.error)throw a.error;if(b.error)throw b.error;userA=a.data.user.id;userB=b.data.user.id;clientA=createClient(url!,publishableKey!,{auth:{persistSession:false,autoRefreshToken:false}});clientB=createClient(url!,publishableKey!,{auth:{persistSession:false,autoRefreshToken:false}});const [la,lb]=await Promise.all([clientA.auth.signInWithPassword({email:emailA,password}),clientB.auth.signInWithPassword({email:emailB,password})]);if(la.error)throw la.error;if(lb.error)throw lb.error;const [ta,tb]=await Promise.all([clientA.rpc('create_tenant',{p_name:'Asset A',p_slug:`asset-a-${run}`}),clientB.rpc('create_tenant',{p_name:'Asset B',p_slug:`asset-b-${run}`})]);if(ta.error)throw ta.error;if(tb.error)throw tb.error;tenantA=ta.data as string;tenantB=tb.data as string;const inserted=await admin.from('brand_assets').insert([{tenant_id:tenantA,kind:'image',storage_bucket:'brand-assets',storage_path:`${tenantA}/assets/a.svg`,original_filename:'pizza.svg',mime_type:'image/svg+xml',content_hash:`a-${run}`,asset_type:'food',status:'ACTIVE',suitable_platforms:['instagram'],tags:['pizza']},{tenant_id:tenantB,kind:'image',storage_bucket:'brand-assets',storage_path:`${tenantB}/assets/b.svg`,original_filename:'camera.svg',mime_type:'image/svg+xml',content_hash:`b-${run}`,asset_type:'interior',status:'ACTIVE',suitable_platforms:['instagram'],tags:['camera']}]).select('id,tenant_id');if(inserted.error)throw inserted.error;assetA=inserted.data.find(x=>x.tenant_id===tenantA)!.id;assetB=inserted.data.find(x=>x.tenant_id===tenantB)!.id;});
 afterAll(async()=>{if(tenantA||tenantB)await admin.from('tenants').delete().in('id',[tenantA,tenantB].filter(Boolean));await Promise.all([userA?admin.auth.admin.deleteUser(userA):Promise.resolve(),userB?admin.auth.admin.deleteUser(userB):Promise.resolve()]);});
 it('hides and protects another tenant asset row',async()=>{const own=await clientA.from('brand_assets').select('id').eq('id',assetA);expect(own.error).toBeNull();expect(own.data).toEqual([{id:assetA}]);const hidden=await clientA.from('brand_assets').select('id').eq('id',assetB);expect(hidden.error).toBeNull();expect(hidden.data).toEqual([]);const patch=await clientA.from('brand_assets').update({description:'attack'}).eq('id',assetB).select('id');expect(patch.error).toBeNull();expect(patch.data).toEqual([]);const del=await clientA.from('brand_assets').delete().eq('id',assetB).select('id');expect(del.error).toBeNull();expect(del.data).toEqual([]);});
 it('derives Storage authorization from the tenant-safe path',async()=>{const svg='<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><rect width="40" height="40" fill="#111"/></svg>';const own=await clientA.storage.from('brand-assets').upload(`${tenantA}/assets/own-${run}.svg`,svg,{contentType:'image/svg+xml'});expect(own.error).toBeNull();const cross=await clientA.storage.from('brand-assets').upload(`${tenantB}/assets/cross-${run}.svg`,svg,{contentType:'image/svg+xml'});expect(cross.error).not.toBeNull();const listB=await clientA.storage.from('brand-assets').list(`${tenantB}/assets`);expect(listB.error).toBeNull();expect(listB.data).toEqual([]);await clientA.storage.from('brand-assets').remove([`${tenantA}/assets/own-${run}.svg`]);});
 it('keeps server-generated visual evidence read-only and tenant-scoped',async()=>{const fake=await clientA.from('visual_renders').insert({tenant_id:tenantA,post_variant_id:crypto.randomUUID(),render_version:1,visual_type:'branded_card',template_key:'minimal_brand_card',format:'square',width:1080,height:1080,fingerprint:'fake'});expect(fake.error).not.toBeNull();const [visibleA,visibleB]=await Promise.all([clientA.from('asset_usage_history').select('tenant_id').eq('tenant_id',tenantB),clientB.from('asset_usage_history').select('tenant_id').eq('tenant_id',tenantA)]);expect(visibleA.error).toBeNull();expect(visibleB.error).toBeNull();expect(visibleA.data).toEqual([]);expect(visibleB.data).toEqual([]);});
 it('rejects a cross-tenant logo reference at the relational boundary',async()=>{const profile=await clientA.from('brand_profiles').insert({tenant_id:tenantA,brand_name:'Asset Brand A',version:1}).select('id').single();expect(profile.error).toBeNull();const cross=await clientA.from('brand_profiles').update({primary_logo_asset_id:assetB}).eq('id',profile.data!.id);expect(cross.error).not.toBeNull();});
});
