import { describe,expect,it } from 'vitest';
import {
  ConnectionLifecycle, EnvelopeCredentialVault, HmacWebhookVerifier, OAuthStateManager, PermissionMatrix, PlanEntitlementGuard,
  PlatformContentValidator, TelegramApprovalCallbacks, WebhookCore, buildFixtureAccounts, createFixtureProvider,
  loadEnvironmentConfig, providerFixtureConfigs, readinessRow,
} from '../src/provider-readiness.js';
import type { NormalizedPublishPayload, OAuthStart, ProviderAccount, ProviderSocialPlatform } from '@socialpilot/contracts';

const tenant='11111111-1111-4111-8111-111111111111';
const user='22222222-2222-4222-8222-222222222222';
const redirect='http://127.0.0.1:8787/oauth/callback';
const oauthInput=(provider:'facebook'|'linkedin'|'google_business_profile'='facebook'):OAuthStart=>({tenantId:tenant,userId:user,provider,redirectUri:redirect,scopes:['scope-a'],usePkce:true});
const payload=(platform:ProviderSocialPlatform,accountId:string,format:string,media:NormalizedPublishPayload['media']=[]):NormalizedPublishPayload=>({platform,accountId,format,text:'Contenuto fixture',media,idempotencyKey:'idem-12345678',correlationId:'corr-12345678'});

function selected(platform:ProviderSocialPlatform,connectionId=`fixture-${platform}`):ProviderAccount { const item=buildFixtureAccounts(platform,connectionId).find((row)=>row.selected)??buildFixtureAccounts(platform,connectionId)[0]; if(!item)throw new Error('fixture_missing');return item; }

describe('environment safety',()=>{
  it('defaults LOCAL to mock and all live flags false',()=>{const config=loadEnvironmentConfig({});expect(config.mode).toBe('LOCAL');expect(config.publishingMode).toBe('MOCK');expect(Object.values(config.flags).every((value)=>value===false)).toBe(true);});
  it('keeps STAGING publishing dry-run by default',()=>{expect(loadEnvironmentConfig({APP_ENV:'STAGING',APP_BASE_URL:'https://staging.example.test'}).publishingMode).toBe('DRY_RUN');});
  it('rejects implicit/unknown environment modes',()=>{expect(()=>loadEnvironmentConfig({APP_ENV:'localhost'})).toThrow('APP_ENV_INVALID');});
});

describe('OAuth state security',()=>{
  it('creates cryptographic state and PKCE S256',()=>{const manager=new OAuthStateManager([redirect]);const auth=manager.start(oauthInput());expect(auth.state.length).toBeGreaterThanOrEqual(32);expect(auth.codeChallengeMethod).toBe('S256');expect(auth.authorizationUrl).toContain('code_challenge=');});
  it('accepts valid state once',()=>{const manager=new OAuthStateManager([redirect]);const auth=manager.start(oauthInput(),1000);expect(manager.consume({state:auth.state,provider:'facebook',tenantId:tenant,userId:user,redirectUri:redirect},1100).codeVerifier).toBeTruthy();expect(()=>manager.consume({state:auth.state,provider:'facebook',tenantId:tenant,userId:user,redirectUri:redirect},1200)).toThrow('OAUTH_STATE_REPLAY');});
  it('rejects modified state',()=>{const manager=new OAuthStateManager([redirect]);const auth=manager.start(oauthInput());expect(()=>manager.consume({state:`${auth.state}x`,provider:'facebook',tenantId:tenant,userId:user,redirectUri:redirect})).toThrow('OAUTH_STATE_INVALID');});
  it('rejects expired state',()=>{const manager=new OAuthStateManager([redirect],100);const auth=manager.start(oauthInput(),1000);expect(()=>manager.consume({state:auth.state,provider:'facebook',tenantId:tenant,userId:user,redirectUri:redirect},1200)).toThrow('OAUTH_STATE_EXPIRED');});
  it('binds state to tenant, user and provider',()=>{const manager=new OAuthStateManager([redirect]);const auth=manager.start(oauthInput());expect(()=>manager.consume({state:auth.state,provider:'facebook',tenantId:'33333333-3333-4333-8333-333333333333',userId:user,redirectUri:redirect})).toThrow('OAUTH_STATE_WRONG_TENANT');const auth2=manager.start(oauthInput());expect(()=>manager.consume({state:auth2.state,provider:'facebook',tenantId:tenant,userId:'44444444-4444-4444-8444-444444444444',redirectUri:redirect})).toThrow('OAUTH_STATE_WRONG_USER');const auth3=manager.start(oauthInput());expect(()=>manager.consume({state:auth3.state,provider:'linkedin',tenantId:tenant,userId:user,redirectUri:redirect})).toThrow('OAUTH_STATE_WRONG_PROVIDER');});
  it('rejects malicious redirect before and after authorization',()=>{const manager=new OAuthStateManager([redirect]);expect(()=>manager.start({...oauthInput(),redirectUri:'https://evil.example/callback'})).toThrow('OAUTH_REDIRECT_NOT_ALLOWED');const auth=manager.start(oauthInput());expect(()=>manager.consume({state:auth.state,provider:'facebook',tenantId:tenant,userId:user,redirectUri:'https://evil.example/callback'})).toThrow('OAUTH_REDIRECT_MISMATCH');});
});

describe('credential vault',()=>{
  it('stores, rotates and deletes encrypted credentials without returning ciphertext as token',()=>{const vault=new EnvelopeCredentialVault(Buffer.alloc(32,9));vault.store('conn',{accessToken:'access-secret',refreshToken:'refresh-secret',scopes:['a']});expect(vault.get('conn').accessToken).toBe('access-secret');expect(vault.rotate('conn',{accessToken:'access-new',scopes:['a','b']}).version).toBe(2);expect(vault.get('conn').accessToken).toBe('access-new');expect(vault.delete('conn')).toBe(true);expect(()=>vault.get('conn')).toThrow('CREDENTIAL_NOT_FOUND');});
});

describe('webhook security/idempotency',()=>{
  it('accepts a signed event then ignores duplicate',()=>{const verifier=new HmacWebhookVerifier('facebook','secret');const core=new WebhookCore();const now=1_700_000_000_000;const raw='{"event":"publish"}';const headers={'x-provider-timestamp':String(now),'x-provider-signature':verifier.sign(raw,now)};expect(core.process({provider:'facebook',eventType:'publish',externalId:'evt-1',rawBody:raw,headers,nowMs:now,verifier}).status).toBe('PROCESSED');expect(core.process({provider:'facebook',eventType:'publish',externalId:'evt-1',rawBody:raw,headers,nowMs:now,verifier}).status).toBe('IGNORED_DUPLICATE');});
  it('rejects forged, stale and malformed webhook',()=>{const verifier=new HmacWebhookVerifier('facebook','secret');const core=new WebhookCore();const now=1_700_000_000_000;expect(()=>core.process({provider:'facebook',eventType:'x',rawBody:'{}',headers:{'x-provider-timestamp':String(now),'x-provider-signature':'sha256=bad'},nowMs:now,verifier})).toThrow('WEBHOOK_SIGNATURE_INVALID');const raw='{}';expect(()=>core.process({provider:'facebook',eventType:'x',rawBody:raw,headers:{'x-provider-timestamp':String(now-600_000),'x-provider-signature':verifier.sign(raw,now-600_000)},nowMs:now,verifier})).toThrow('WEBHOOK_SIGNATURE_INVALID');const headers={'x-provider-timestamp':String(now),'x-provider-signature':verifier.sign('no-json',now)};expect(()=>core.process({provider:'facebook',eventType:'x',rawBody:'no-json',headers,nowMs:now,verifier})).toThrow('WEBHOOK_MALFORMED_PAYLOAD');});
});

describe('provider contract/capabilities',()=>{
  for(const platform of ['facebook','instagram','linkedin','google_business_profile'] as const){
    it(`${platform} supports accounts, validation, dry-run, publish, reconcile, analytics and disconnect`,async()=>{const connection=`fixture-${platform}`;const provider=createFixtureProvider(platform,connection);const accounts=await provider.listAccounts(connection);expect(accounts.length).toBeGreaterThan(0);const account=accounts.find((item)=>item.selected)??accounts[0]!;const format=platform==='google_business_profile'?'local_post':platform==='instagram'?'image':'text';const media=format==='image'?[{mimeType:'image/jpeg',url:'https://fixture.invalid/image.jpg'}]:[];const input=payload(platform,account.id,format,media);expect((await provider.capabilities(account)).length).toBeGreaterThan(0);const validation=await provider.validateContent(account,input);expect(validation.valid).toBe(true);expect((await provider.dryRun(account,input)).wouldPublish).toBe(true);const published=await provider.publish(account,input);expect(published.externalPostId).toBeTruthy();expect((await provider.reconcile({connectionId:connection,accountId:account.id,idempotencyKey:input.idempotencyKey}))?.externalPostId).toBe(published.externalPostId);expect((await provider.analytics({connectionId:connection,accountId:account.id,externalPostId:published.externalPostId})).availableMetricKeys.length).toBeGreaterThan(0);await provider.disconnect(connection);expect((await provider.validateConnection(connection)).status).toBe('REAUTH_REQUIRED');});
  }
  it('models connection independently from multiple accounts',async()=>{expect((await createFixtureProvider('facebook','fixture-facebook').listAccounts('fixture-facebook')).length).toBe(2);expect((await createFixtureProvider('linkedin','fixture-linkedin').listAccounts('fixture-linkedin')).length).toBe(2);expect((await createFixtureProvider('google_business_profile','fixture-google_business_profile').listAccounts('fixture-google_business_profile')).length).toBe(2);});
  it('does not invent LinkedIn organic carousel support',()=>{const validator=new PlatformContentValidator();const account=selected('linkedin');const result=validator.validate(providerFixtureConfigs.linkedin,account,payload('linkedin',account.id,'carousel'));expect(result.valid).toBe(false);expect(result.issues.some((issue)=>issue.code==='LINKEDIN_ORGANIC_CAROUSEL_UNSUPPORTED')).toBe(true);});
  it('blocks unsupported GBP product post and CTA',()=>{const validator=new PlatformContentValidator();const account=selected('google_business_profile');expect(validator.validate(providerFixtureConfigs.google_business_profile,account,payload('google_business_profile',account.id,'product')).issues.some((issue)=>issue.code==='GBP_PRODUCT_POST_UNSUPPORTED')).toBe(true);const bad={...payload('google_business_profile',account.id,'local_post'),cta:'DOWNLOAD'};expect(validator.validate(providerFixtureConfigs.google_business_profile,account,bad).issues.some((issue)=>issue.code==='CTA_UNSUPPORTED')).toBe(true);});
  it('permission matrix returns actionable required scopes',()=>{const matrix=new PermissionMatrix();const account={...selected('instagram'),grantedScopes:[],missingPermissions:[]};expect(matrix.missing('instagram','publish_post',account)).toContain('instagram_content_publish');});
});

describe('connection health/reconnect lifecycle',()=>{
  it('moves connected -> expiring -> reauth required -> connected',()=>{const lifecycle=new ConnectionLifecycle();const now=1_700_000_000_000;expect(lifecycle.status({nowMs:now,expiresAtMs:now+30*86400_000,connected:true})).toBe('CONNECTED');expect(lifecycle.status({nowMs:now,expiresAtMs:now+2*86400_000,connected:true})).toBe('EXPIRING');expect(lifecycle.status({nowMs:now,expiresAtMs:now-1,connected:true})).toBe('REAUTH_REQUIRED');expect(lifecycle.status({nowMs:now,expiresAtMs:now+30*86400_000,connected:true})).toBe('CONNECTED');});
});

describe('plan enforcement',()=>{
  const guard=new PlanEntitlementGuard();const starter={platforms:['instagram'],postsPerWeek:2,monthlyPostLimit:5,autoPublishAllowed:false,imageGenerationAllowed:false,analyticsLevel:'basic',premiumChatAllowed:false};
  it('blocks Pro-only/platform/quota capabilities server-side',()=>{expect(()=>guard.assertPlatform(starter,'linkedin')).toThrow('FEATURE_NOT_ENTITLED:platform');expect(()=>guard.assertAutoPublish(starter)).toThrow('FEATURE_NOT_ENTITLED:auto_publish');expect(()=>guard.assertImageGeneration(starter)).toThrow('FEATURE_NOT_ENTITLED:image_generation');expect(()=>guard.assertAdvancedAnalytics(starter)).toThrow('FEATURE_NOT_ENTITLED:advanced_analytics');expect(()=>guard.assertPosts(starter,2,2,1)).toThrow('QUOTA_EXCEEDED:posts_week');expect(()=>guard.assertPosts(starter,1,5,1)).toThrow('QUOTA_EXCEEDED:posts_month');});
});

describe('Telegram callback security',()=>{
  it('blocks forged, replay, tenant mismatch and unauthorized chat',()=>{const callbacks=new TelegramApprovalCallbacks('telegram-secret');const issued=callbacks.issue({tenantId:tenant,chatId:'chat-1',postVariantId:'variant-1',action:'approve'},1000);expect(callbacks.verify({...issued,tenantId:tenant,chatId:'chat-1'},1100).action).toBe('approve');expect(()=>callbacks.verify({...issued,tenantId:tenant,chatId:'chat-1'},1200)).toThrow('TELEGRAM_CALLBACK_REPLAY');const tenantMismatch=callbacks.issue({tenantId:tenant,chatId:'chat-1',postVariantId:'v',action:'reject'},1000);expect(()=>callbacks.verify({...tenantMismatch,tenantId:'33333333-3333-4333-8333-333333333333',chatId:'chat-1'},1100)).toThrow('TELEGRAM_TENANT_MISMATCH');const chatMismatch=callbacks.issue({tenantId:tenant,chatId:'chat-1',postVariantId:'v',action:'open'},1000);expect(()=>callbacks.verify({...chatMismatch,tenantId:tenant,chatId:'chat-2'},1100)).toThrow('TELEGRAM_CHAT_UNAUTHORIZED');expect(()=>callbacks.verify({data:chatMismatch.data,signature:'bad',tenantId:tenant,chatId:'chat-1'},1100)).toThrow('TELEGRAM_CALLBACK_FORGED');});
});

describe('readiness score',()=>{it('distinguishes ready-for-credentials from live validated',()=>{const base={ARCHITECTURE:true,CONTRACTS:true,FIXTURES:true,TESTS:true,UI:true,SECURITY:true,DOCUMENTATION:true};expect(readinessRow('Meta',base).status).toBe('READY_FOR_CREDENTIALS');expect(readinessRow('Meta',{...base,LIVE_CREDENTIALS:true,REMOTE_CALLBACKS:true}).status).toBe('LIVE_VALIDATED');});});
