import { describe,expect,it } from 'vitest';
import { MockStripeLifecycleFixture } from '../src/stripe-lifecycle-fixture.js';

describe('Stripe lifecycle hardening',()=>{
  it('checkout webhook creates active subscription and duplicate webhook is ignored',()=>{const stripe=new MockStripeLifecycleFixture();const event={eventId:'evt-checkout-1',type:'checkout.session.completed' as const,tenantId:'tenant-a',subscriptionId:'sub-a',planCode:'starter'};const first=stripe.processWebhook(event);const duplicate=stripe.processWebhook(event);expect(first).toMatchObject({processed:true,duplicate:false,subscription:{planCode:'starter',status:'active'}});expect(duplicate).toMatchObject({processed:false,duplicate:true});expect(duplicate.subscription?.entitlementsVersion).toBe(first.subscription?.entitlementsVersion);});
  it('payment failure moves subscription to past_due and entitlement sync reflects it',()=>{const stripe=new MockStripeLifecycleFixture();stripe.seed({tenantId:'tenant-a',subscriptionId:'sub-a',planCode:'starter'});stripe.processWebhook({eventId:'evt-failed-1',type:'invoice.payment_failed',tenantId:'tenant-a',subscriptionId:'sub-a'});expect(stripe.syncEntitlements('sub-a')).toMatchObject({status:'past_due',planCode:'starter',synced:true});});
  it('upgrade and downgrade update the same subscription identity',()=>{const stripe=new MockStripeLifecycleFixture();stripe.seed({tenantId:'tenant-a',subscriptionId:'sub-a',planCode:'starter'});stripe.processWebhook({eventId:'evt-up-1',type:'customer.subscription.updated',tenantId:'tenant-a',subscriptionId:'sub-a',planCode:'pro'});expect(stripe.get('sub-a')).toMatchObject({subscriptionId:'sub-a',planCode:'pro',status:'active'});stripe.processWebhook({eventId:'evt-down-1',type:'customer.subscription.updated',tenantId:'tenant-a',subscriptionId:'sub-a',planCode:'starter'});expect(stripe.get('sub-a')).toMatchObject({subscriptionId:'sub-a',planCode:'starter',status:'active'});});
  it('cancel-at-period-end and deleted events preserve deterministic state transitions',()=>{const stripe=new MockStripeLifecycleFixture();stripe.seed({tenantId:'tenant-a',subscriptionId:'sub-a',planCode:'pro'});stripe.processWebhook({eventId:'evt-cancel-scheduled',type:'customer.subscription.updated',tenantId:'tenant-a',subscriptionId:'sub-a',atPeriodEnd:true});expect(stripe.get('sub-a')?.status).toBe('cancel_at_period_end');stripe.processWebhook({eventId:'evt-deleted',type:'customer.subscription.deleted',tenantId:'tenant-a',subscriptionId:'sub-a'});expect(stripe.get('sub-a')?.status).toBe('canceled');});
});
