import { describe, expect, it } from 'vitest';
import { AssetSelectionEngine, DeterministicAssetClassifier, DeterministicGraphicRenderer, DeterministicVisualDirector, ImagePromptBuilder, MockImageGenerationProvider, SelectiveQaRepairEngine, buildCarouselSlides, deriveVisualTemplateProfile, type RepairableVariant, type VisualAsset } from '../src/visual-engine.js';

const asset=(overrides:Partial<VisualAsset>={}):VisualAsset=>({id:'a1',tenantId:'tenant-a',assetType:'food',mimeType:'image/jpeg',filename:'pizza-margherita.jpg',tags:['pizza','margherita','food'],suitablePlatforms:['instagram','facebook','linkedin','google_business_profile'],suitableTopics:['pizza','margherita'],qualityScore:.95,isBrandLocked:false,isPreferred:true,status:'ACTIVE',usageCount:0,lastUsedAt:null,...overrides});
const brief={objective:'Consideration',headline:'La margherita come deve essere',supportingText:'Impasto, pomodoro e mozzarella raccontati senza sovraccaricare la grafica.',cta:'Prenota il tuo tavolo'};

describe('visual engine',()=>{
  it('classifies common local business assets deterministically',()=>{const c=new DeterministicAssetClassifier();expect(c.classify({filename:'pizza-margherita.jpg',mimeType:'image/jpeg',width:1600,height:1200}).assetType).toBe('food');expect(c.classify({filename:'logo-dark.svg',mimeType:'image/svg+xml',width:800,height:300}).assetType).toBe('logo_alt');expect(c.classify({filename:'brochure-servizi.pdf',mimeType:'application/pdf',width:null,height:null}).assetType).toBe('brochure')});
  it('prefers a relevant real pizza photo over generation',()=>{const result=new AssetSelectionEngine().select({tenantId:'tenant-a',topic:'pizza margherita',pillar:'prodotti',platform:'instagram',format:'square',brief,assets:[asset()],usage:[],now:'2026-08-10T06:00:00Z'});expect(result.decision).toBe('real_asset');expect(result.selectedAssetId).toBe('a1');expect(result.generatedVisualRequired).toBe(false)});
  it('penalizes repeated assets and can choose another relevant photo',()=>{const engine=new AssetSelectionEngine();const result=engine.select({tenantId:'tenant-a',topic:'pizza margherita',pillar:'prodotti',platform:'instagram',format:'square',brief,assets:[asset(),asset({id:'a2',filename:'pizza-forno.jpg',tags:['pizza','forno'],isPreferred:false})],usage:[{assetId:'a1',usedAt:'2026-08-09T10:00:00Z'},{assetId:'a1',usedAt:'2026-08-08T10:00:00Z'},{assetId:'a1',usedAt:'2026-08-07T10:00:00Z'}],now:'2026-08-10T06:00:00Z'});expect(result.selectedAssetId).toBe('a2')});
  it('falls back to branded graphic without useful assets',()=>{const result=new AssetSelectionEngine().select({tenantId:'tenant-a',topic:'guida locale',pillar:'education',platform:'linkedin',format:'landscape',brief,assets:[],usage:[],now:'2026-08-10T06:00:00Z'});expect(result.decision).toBe('branded_graphic')});
  it('requests mock generation only when photorealism is explicitly required',()=>{const result=new AssetSelectionEngine().select({tenantId:'tenant-a',topic:'concept futuro',pillar:'brand',platform:'instagram',format:'portrait',brief:{...brief,requiresPhotorealism:true},assets:[],usage:[],now:'2026-08-10T06:00:00Z'});expect(result.decision).toBe('generated_visual');expect(result.generatedVisualRequired).toBe(true)});
  it('derives different tenant visual profiles',()=>{expect(deriveVisualTemplateProfile('tenant-a')).not.toEqual(deriveVisualTemplateProfile('tenant-b'))});
  it('renders real SVG previews with centralized formats and visual QA',()=>{const renderer=new DeterministicGraphicRenderer();const result=renderer.render({tenantId:'tenant-a',platform:'instagram',format:'square',visualType:'branded_card',templateKey:'minimal_brand_card',headline:'Tre consigli utili',supportingText:'Testo leggibile e sintetico.',cta:'Scopri di più',palette:['#111827','#ffffff','#f59e0b'],fontFamily:'Inter, sans-serif',logoPosition:'top_right',forbiddenClaims:[]});expect(result.status).toBe('ready');expect(result.svg).toContain('<svg');expect(result.width).toBe(1080);expect(result.height).toBe(1080)});
  it('blocks forbidden factual claims inside graphics',()=>{const result=new DeterministicGraphicRenderer().render({tenantId:'tenant-a',platform:'facebook',format:'square',visualType:'promotional',templateKey:'promotional',headline:'Il miglior ristorante di Milano',supportingText:'Prenota oggi',cta:'Prenota',palette:['#111827','#ffffff','#f59e0b'],fontFamily:'Inter',logoPosition:'top_left',forbiddenClaims:['miglior ristorante di milano']});expect(result.status).toBe('qa_failed');expect(result.issues.some((issue)=>issue.code==='FORBIDDEN_FACT_CLAIM')).toBe(true)});
  it('selective repair changes only the affected component',()=>{const original:RepairableVariant={hook:'Un hook molto lungo '.repeat(8),caption:'Caption buona',hashtags:['#pizza','#milano'],cta:'Prenota',visual:{templateKey:'photo_text_overlay',headline:'Titolo',supportingText:'Body'}};const repaired=new SelectiveQaRepairEngine().repair({component:'hook',variant:original,issueCode:'HOOK_LOW_SCORE',variantSeed:4}).variant;expect(repaired.hook).not.toBe(original.hook);expect(repaired.caption).toBe(original.caption);expect(repaired.cta).toBe(original.cta);expect(repaired.visual).toEqual(original.visual)});
  it('rotates only the visual template for repetition',()=>{const original:RepairableVariant={hook:'Hook',caption:'Caption',hashtags:['#one'],cta:'CTA',visual:{templateKey:'photo_text_overlay',headline:'Titolo',supportingText:'Body'}};const repaired=new SelectiveQaRepairEngine().repair({component:'visual',variant:original,issueCode:'TEMPLATE_REPETITION',variantSeed:2}).variant;expect(repaired.visual.templateKey).not.toBe(original.visual.templateKey);expect(repaired.caption).toBe(original.caption);expect(repaired.hook).toBe(original.hook)});
  it('renders structured carousel slide data',()=>{const slides=buildCarouselSlides({type:'checklist',headline:'Checklist apertura casa',supportingText:'Controlla questi elementi prima dell’arrivo.',cta:'Salva la checklist'});expect(slides).toHaveLength(5);expect(slides[0]?.layout).toBe('cover');expect(slides.at(-1)?.layout).toBe('cta')});
  it('builds safe image prompts and mock generation without external calls',async()=>{const prompt=new ImagePromptBuilder().build({brandName:'CasaChiara',visualBrief:brief,content:'ospitalità locale',platform:'instagram',style:'natural photography',forbiddenElements:['fake reviews'],assetReferences:['a1'],photographicDirection:'soft daylight'});expect(prompt.forbiddenElements).toContain('invented logos');const generated=await new MockImageGenerationProvider().generate({tenantId:'tenant-a',prompt:prompt.prompt,format:'portrait',forbiddenElements:prompt.forbiddenElements,referenceAssetIds:prompt.referenceAssetIds});expect(generated.provider).toBe('mock');expect(generated.dataUri).toMatch(/^data:image\/svg\+xml;base64,/)});
  it('visual director emits structured branded direction',()=>{const profile=deriveVisualTemplateProfile('tenant-a');const direction=new DeterministicVisualDirector().direct({tenantId:'tenant-a',platform:'instagram',format:'square',topic:'pizza margherita',brief,selection:{decision:'real_asset',selectedAssetId:'a1',generatedVisualRequired:false,motivationCode:'REAL_ASSET_HIGH_RELEVANCE',confidence:.9,score:90},profile,recentFingerprints:[]});expect(direction.selectedAssetIds).toEqual(['a1']);expect(direction.brandElements).toContain('palette');expect(direction.templateKey).toBeTruthy()});
});
