import { describe, expect, it } from 'vitest';
import { DeterministicGraphicRenderer, SelectiveQaRepairEngine, type RepairableVariant } from '../src/visual-engine.js';
const base=():RepairableVariant=>({hook:'Hook valido',caption:'Caption valida e già approvata',hashtags:['pizza','milano','pizza'],cta:'CTA valida',visual:{templateKey:'photo_text_overlay',headline:'Titolo valido',supportingText:'Body valido'}});

describe('selective visual QA hardening',()=>{
  it('repairs only an oversized caption',()=>{const original=base();original.caption='Caption molto lunga '.repeat(40);const result=new SelectiveQaRepairEngine().repair({component:'caption',variant:original,issueCode:'CAPTION_TOO_LONG',variantSeed:3});expect(result.variant.caption.length).toBeLessThanOrEqual(420);expect(result.variant.hook).toBe(original.hook);expect(result.variant.cta).toBe(original.cta);expect(result.variant.visual).toEqual(original.visual)});
  it('repairs only a weak/long CTA',()=>{const original=base();original.cta='Scopri assolutamente tutto quello che puoi fare cliccando subito qui per maggiori dettagli';const result=new SelectiveQaRepairEngine().repair({component:'cta',variant:original,issueCode:'CTA_LOW_SCORE',variantSeed:4});expect(result.variant.cta.length).toBeLessThanOrEqual(34);expect(result.variant.caption).toBe(original.caption);expect(result.variant.hook).toBe(original.hook);expect(result.variant.visual).toEqual(original.visual)});
  it('repairs hashtags without touching copy or visual',()=>{const original=base();original.hashtags=['pizza','pizza','#milano','delivery veloce','#quartiere','#sera','#forno','#impasto','#extra','#troppo'];const result=new SelectiveQaRepairEngine().repair({component:'hashtags',variant:original,issueCode:'HASHTAGS_LOW_SCORE',variantSeed:2});expect(result.variant.hashtags.length).toBeLessThanOrEqual(8);expect(new Set(result.variant.hashtags).size).toBe(result.variant.hashtags.length);expect(result.variant.hashtags.every(tag=>tag.startsWith('#'))).toBe(true);expect(result.variant.caption).toBe(original.caption);expect(result.variant.visual).toEqual(original.visual)});
  it('detects visual text overflow and low contrast without crashing',()=>{const renderer=new DeterministicGraphicRenderer();const result=renderer.render({tenantId:'qa',platform:'instagram',format:'square',visualType:'branded_card',templateKey:'minimal_brand_card',headline:'Titolo volutamente troppo lungo '.repeat(6),supportingText:'Body volutamente troppo lungo '.repeat(15),cta:'Una call to action che è volutamente troppo lunga per stare bene',palette:['#777777','#787878','#999999'],fontFamily:'Inter',logoPosition:'top_right',forbiddenClaims:[]});expect(result.status).toBe('qa_failed');expect(result.issues.map(issue=>issue.code)).toEqual(expect.arrayContaining(['HEADLINE_TOO_LONG','BODY_TOO_LONG','CTA_TOO_LONG','LOW_CONTRAST']))});
  it('rotates template only when template repetition is the issue',()=>{const original=base();const result=new SelectiveQaRepairEngine().repair({component:'visual',variant:original,issueCode:'TEMPLATE_REPETITION',variantSeed:5});expect(result.repairAction).toBe('rotate_template_only');expect(result.variant.visual.templateKey).not.toBe(original.visual.templateKey);expect(result.variant.caption).toBe(original.caption);expect(result.variant.hook).toBe(original.hook);expect(result.variant.cta).toBe(original.cta)});
});
