import type { ReactNode } from 'react';
import { Link } from 'react-router';
import { Seo } from '../components/Seo';

const ReviewNotice=()=> <div className="legal-review-notice" role="note"><strong>DA REVISIONARE PRIMA DEL LANCIO COMMERCIALE</strong><p>Questa pagina è una base tecnica e informativa. Non costituisce una revisione legale professionale né una dichiarazione di conformità definitiva.</p></div>;
const Shell=({title,description,children}:{title:string;description:string;children:ReactNode})=><main className="public-page legal-page"><Seo title={`${title} | SocialPilot AI`} description={description}/><header className="legal-hero"><Link to="/" className="brand-mark">SocialPilot AI</Link><span className="eyebrow">Documenti pubblici</span><h1>{title}</h1><p>{description}</p></header><ReviewNotice/><article className="legal-content">{children}</article><nav className="legal-links" aria-label="Documenti legali"><Link to="/privacy">Privacy Policy</Link><Link to="/termini">Termini e Condizioni</Link><Link to="/cookie-policy">Cookie Policy</Link><Link to="/">Torna al sito</Link></nav></main>;

export function PrivacyPage(){return <Shell title="Privacy Policy" description="Base della policy privacy per sito pubblico, account SaaS e integrazioni collegate."><h2>Dati trattati</h2><p>La piattaforma è progettata per trattare dati account, dati del workspace, contenuti caricati, configurazioni del brand, log operativi e dati restituiti dalle integrazioni autorizzate. La versione commerciale dovrà specificare titolare, basi giuridiche, categorie effettive, conservazione e destinatari.</p><h2>Integrazioni e revoca</h2><p>Le connessioni social devono poter essere revocate. Token e secret sono previsti esclusivamente lato server e non devono essere esposti al browser.</p><h2>Diritti e cancellazione</h2><p>L'architettura prevede richiesta di cancellazione account/tenant, audit del processo e cleanup dei dati applicativi. Tempi di conservazione e procedura definitiva devono essere validati prima del lancio commerciale.</p><h2>Contatti</h2><p>I dati identificativi e di contatto definitivi del titolare saranno inseriti prima del lancio commerciale.</p></Shell>}
export function TermsPage(){return <Shell title="Termini e Condizioni" description="Base dei termini di utilizzo del SaaS, senza condizioni commerciali definitive."><h2>Servizio</h2><p>Il prodotto assiste nella creazione, approvazione, programmazione, pubblicazione e analisi di contenuti social. Funzioni e provider disponibili dipendono dalle integrazioni realmente attive e dalle quote assegnate al tenant.</p><h2>Account e sicurezza</h2><p>L'utente è responsabile delle proprie credenziali e delle autorizzazioni concesse alle piattaforme esterne. Il servizio può sospendere un tenant per sicurezza, abuso o superamento delle condizioni operative.</p><h2>Contenuti e approvazioni</h2><p>L'utente resta responsabile dei contenuti pubblicati e delle informazioni fornite al sistema. Le modalità AUTO e MANUALE devono rispettare i controlli di piano e le impostazioni del tenant.</p><h2>Prezzi</h2><p>Finché il checkout non è attivo, l'accesso può essere abilitato manualmente dall'amministratore. Questa bozza non definisce prezzi, rinnovi, recesso o condizioni fiscali definitive.</p></Shell>}
export function CookiePolicyPage(){return <Shell title="Cookie Policy" description="Base tecnica per descrivere cookie e storage realmente utilizzati dalla versione online."><h2>Necessari</h2><p>La piattaforma può usare storage o cookie strettamente necessari per autenticazione, sessione, sicurezza e preferenze operative. L'elenco definitivo deve essere ricavato dalla configurazione realmente distribuita.</p><h2>Analytics e marketing</h2><p>Nessun cookie opzionale deve essere dichiarato come attivo se non lo è realmente. Se in futuro saranno introdotti strumenti analytics o marketing che richiedono consenso, il banner e le preferenze dovranno essere aggiornati prima dell'attivazione.</p><h2>Gestione preferenze</h2><p>La versione commerciale dovrà indicare durata, fornitore, finalità e modalità di revoca per ogni tecnologia non strettamente necessaria.</p></Shell>}
