import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router';
import { Badge, Card, EmptyState, PageHeader } from '../components/ui';
import { useLocalE2E } from '../services/local-e2e';
import './provider-readiness.css';

type Account={id:string;provider?:string;platform?:string;display_name?:string;displayName?:string;external_account_id?:string;externalAccountId?:string;account_type?:string;accountType?:string;is_selected?:boolean;selected?:boolean;health_status?:string;health?:string;missing_permissions?:string[];missingPermissions?:string[];last_checked_at?:string;lastCheckedAt?:string;last_publish_at?:string;lastPublishAt?:string;};
type Connection={id:string;platform:string;provider:string;connection_status:string;health:string;token_expires_at?:string|null;last_checked_at?:string|null;last_publish_at?:string|null;last_error_message?:string|null;recommended_action?:string|null;accounts:Account[];};
const providerButtons=[['meta','Meta / Facebook + Instagram'],['linkedin','LinkedIn'],['google_business_profile','Google Business Profile']] as const;
const good=(status:string)=>status==='CONNECTED'||status==='connected';
const accountName=(a:Account)=>a.display_name??a.displayName??a.external_account_id??a.externalAccountId??a.id;
const accountPlatform=(a:Account)=>String(a.provider??a.platform??'unknown');
const selected=(a:Account)=>Boolean(a.is_selected??a.selected);
const missing=(a:Account)=>a.missing_permissions??a.missingPermissions??[];

export function ProviderConnectionsPage(){
  const local=useLocalE2E();const [connections,setConnections]=useState<Connection[]>([]);const [message,setMessage]=useState<string|null>(null);const [busy,setBusy]=useState('');
  const load=async()=>{if(!local.tenantId)return;setConnections(await local.api<Connection[]>(`/tenants/${local.tenantId}/provider-connections`));};
  useEffect(()=>{if(local.enabled&&local.tenantId)void load()},[local.enabled,local.tenantId]);
  if(!local.enabled||!local.tenantId)return <><PageHeader eyebrow="Provider" title="Social Connections" description="Local E2E richiesto."/></>;
  const connect=async(provider:string)=>{setBusy(provider);try{await local.api(`/tenants/${local.tenantId}/providers/${provider}/connect-mock`,{method:'POST'});await load();setMessage(`${provider} collegato tramite OAuth fixture. Nessun provider reale contattato.`)}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
  const connectionAction=async(connectionId:string,action:'reconnect'|'revoke')=>{setBusy(`${connectionId}:${action}`);try{await local.api(`/tenants/${local.tenantId}/provider-connections/${connectionId}/${action}`,{method:'POST'});await load();setMessage(action==='reconnect'?'Connessione aggiornata senza perdere storico o published IDs.':'Connessione revocata; storico preservato.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setBusy('')}};
  const choose=async(connectionId:string,accountId:string)=>{try{await local.api(`/tenants/${local.tenantId}/provider-accounts/${accountId}/select`,{method:'POST',body:JSON.stringify({connectionId})});await load();setMessage('Account selezionato per il provider.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}};
  return <><PageHeader eyebrow="OAuth fixture · DB-backed" title="Social Connections & Health" description="Connection e Account sono separati. Token e secret non sono mai esposti al browser." action={<Link className="button secondary" to="/admin/providers">Provider Test Console</Link>}/>{message&&<Card><p role="status">{message}</p></Card>}<Card><div className="provider-connect-actions">{providerButtons.map(([key,label])=><button type="button" data-testid={`connect-${key}`} className="button secondary" disabled={Boolean(busy)} key={key} onClick={()=>void connect(key)}>{busy===key?'Connessione…':`Connetti mock ${label}`}</button>)}</div><p className="muted">La fixture Meta restituisce più Facebook Pages e un Instagram professionale associato. LinkedIn e GBP restituiscono più identità/account dove previsto.</p></Card>{connections.length===0?<Card><EmptyState title="Nessuna connessione provider" body="Usa i bottoni mock per verificare OAuth, account discovery e health senza credenziali reali."/></Card>:<div className="provider-connection-grid">{connections.map((connection)=><Card key={connection.id} className="provider-connection-card"><div className="row-between"><div><span className="eyebrow">{connection.provider}</span><h2>{connection.platform}</h2></div><Badge tone={good(connection.health)?'good':'warn'}>{connection.health}</Badge></div><HealthRows connection={connection}/><div className="provider-account-list">{connection.accounts.map((account)=><button type="button" className={`provider-account ${selected(account)?'selected':''}`} key={account.id} onClick={()=>void choose(connection.id,account.id)}><div><strong>{accountName(account)}</strong><small>{accountPlatform(account)} · {account.account_type??account.accountType??'account'}</small></div><Badge tone={missing(account).length?'warn':selected(account)?'good':'neutral'}>{missing(account).length?`Manca ${missing(account).length} perm.`:selected(account)?'Selezionato':'Disponibile'}</Badge></button>)}</div><div className="card-actions"><button type="button" data-testid={`reconnect-${connection.id}`} className="button secondary" onClick={()=>void connectionAction(connection.id,'reconnect')}>Ricollega / aggiorna permessi</button><button type="button" className="button secondary" onClick={()=>void connectionAction(connection.id,'revoke')}>Revoca</button></div></Card>)}</div>}</>;
}

function HealthRows({connection}:{connection:Connection}){return <div className="connection-health-rows"><div><span>Ultima verifica</span><strong>{connection.last_checked_at?new Date(connection.last_checked_at).toLocaleString('it-IT'):'—'}</strong></div><div><span>Scadenza</span><strong>{connection.token_expires_at?new Date(connection.token_expires_at).toLocaleDateString('it-IT'):'non esposta'}</strong></div><div><span>Ultima pubblicazione</span><strong>{connection.last_publish_at?new Date(connection.last_publish_at).toLocaleString('it-IT'):'—'}</strong></div><div><span>Ultimo errore</span><strong>{connection.last_error_message??'nessuno'}</strong></div>{connection.recommended_action&&<div className="health-action"><span>Azione consigliata</span><strong>{connection.recommended_action}</strong></div>}</div>}

export function ProviderTestConsolePage(){
  const local=useLocalE2E();const [adminReady,setAdminReady]=useState(false);const [connections,setConnections]=useState<Connection[]>([]);const [selectedAccount,setSelectedAccount]=useState('');const [result,setResult]=useState<unknown>(null);const [message,setMessage]=useState<string|null>(null);const [scenario,setScenario]=useState('success');
  const accounts=useMemo(()=>connections.flatMap((connection)=>connection.accounts.map((account)=>({connection,account}))),[connections]);
  const hydrateConnections=async()=>{if(!local.tenantId)return;const rows=await local.api<Connection[]>(`/tenants/${local.tenantId}/provider-connections`);setConnections(rows);const firstAccountId=rows.flatMap((item)=>item.accounts)[0]?.id??'';setSelectedAccount((current)=>current||firstAccountId);};
  const load=async()=>{try{await local.api('/admin');setAdminReady(true);await hydrateConnections();setMessage(null)}catch(e){setAdminReady(false);setMessage(e instanceof Error?e.message:String(e))}};
  useEffect(()=>{if(local.enabled&&local.tenantId)void load()},[local.enabled,local.tenantId]);
  if(!local.enabled||!local.tenantId)return <PageHeader eyebrow="Admin" title="Provider Test Console" description="Local E2E richiesto."/>;
  const grant=async()=>{try{await local.api('/dev/grant-platform-admin',{method:'POST'});setAdminReady(true);await hydrateConnections();setMessage('Console dev abilitata per l’utente locale corrente.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}};
  const pair=accounts.find((item)=>item.account.id===selectedAccount);
  const fixturePayload=()=>{if(!pair)throw new Error('Seleziona un account');const platform=accountPlatform(pair.account);const format=platform==='google_business_profile'?'local_post':platform==='instagram'?'image':'text';return{platform,accountId:pair.account.id,format,text:'Provider readiness dry-run fixture',media:format==='image'?[{mimeType:'image/jpeg',url:'https://fixture.invalid/media.jpg'}]:[],idempotencyKey:`dryrun-${pair.account.id.slice(0,8)}`,correlationId:`console-${Date.now()}`}};
  const accountAction=async(action:'validate'|'dry-run'|'mock-publish'|'analytics')=>{if(!pair)return;try{const body=action==='analytics'?undefined:JSON.stringify(fixturePayload());const path=action==='analytics'?`/tenants/${local.tenantId}/provider-accounts/${pair.account.id}/analytics?externalPostId=fixture-post`:`/tenants/${local.tenantId}/provider-accounts/${pair.account.id}/${action}`;setResult(await local.api(path,{method:action==='analytics'?'GET':'POST',body}));setMessage(`${action} completato su fixture.`)}catch(e){setMessage(e instanceof Error?e.message:String(e))}};
  const simulate=async()=>{if(!pair)return;await local.api(`/tenants/${local.tenantId}/provider-connections/${pair.connection.id}/simulate`,{method:'POST',body:JSON.stringify({scenario})});await hydrateConnections();setMessage(`Scenario ${scenario} applicato.`)};
  return <><PageHeader eyebrow="Dev/Admin only" title="Provider Test Console" description="Connection test, account discovery, validator, dry-run, success/failure simulation e analytics fixture. Nessun token viene mostrato." action={<Link className="button secondary" to="/app/connections">← Connessioni</Link>}/>{message&&<Card><p role={adminReady?'status':'alert'}>{message}</p></Card>}{!adminReady?<Card><EmptyState title="Platform admin richiesto" body="La console provider è disponibile solo dopo il claim admin locale usato dalla suite E2E."/><button type="button" className="button" data-testid="provider-console-claim-admin" onClick={()=>void grant()}>Claim admin locale</button></Card>:<><Card><div className="provider-console-controls"><label>Account<select data-testid="provider-console-account" value={selectedAccount} onChange={(e)=>setSelectedAccount(e.target.value)}><option value="">Seleziona</option>{accounts.map(({account})=><option value={account.id} key={account.id}>{accountName(account)} · {accountPlatform(account)}</option>)}</select></label><label>Scenario<select data-testid="provider-console-scenario" value={scenario} onChange={(e)=>setScenario(e.target.value)}>{['success','timeout','rate_limit','expired','permission_missing','rejected','provider_error'].map((item)=><option key={item}>{item}</option>)}</select></label><button type="button" className="button secondary" onClick={()=>void simulate()}>Simula scenario</button></div><div className="provider-connect-actions"><button type="button" data-testid="provider-console-validate" onClick={()=>void accountAction('validate')}>Validate post</button><button type="button" data-testid="provider-console-dry-run" onClick={()=>void accountAction('dry-run')}>DRY RUN</button><button type="button" onClick={()=>void accountAction('mock-publish')}>Mock publish</button><button type="button" onClick={()=>void accountAction('analytics')}>Analytics fixture</button></div></Card><Card><h2>Output normalizzato</h2><pre className="provider-output" data-testid="provider-console-output">{JSON.stringify(result,null,2)}</pre></Card></>}</>;
}
