import { useMemo } from 'react';
import { Link } from 'react-router';
import { Badge, Card } from '../components/ui';
import { Seo, softwareSchemas } from '../components/Seo';

const platformLabels = ['Instagram', 'Facebook', 'LinkedIn', 'Google Business Profile'];
const faqItems = [
  ['Devo collegare i miei social?', 'Sì, per pubblicare è necessario autorizzare gli account che vuoi gestire. Finché un provider non è collegato, Post Automatici lo mostra chiaramente come da configurare e non finge una connessione attiva.'],
  ['Posso approvare i post prima che escano?', 'Sì. Ogni contenuto generato deve essere mostrato in anteprima e richiede sempre una tua decisione esplicita prima della pubblicazione. Puoi approvare dal sito oppure da Telegram quando il bot è configurato.'],
  ['Cosa significa pubblicazione automatica?', 'Significa soltanto che, dopo una tua approvazione esplicita, il contenuto può essere pubblicato automaticamente all’orario programmato. L’automazione non può saltare anteprima e approvazione umana.'],
  ['Crea anche le immagini?', 'Sì. Quando viene richiesta una nuova immagine generata dall’AI, Post Automatici usa esclusivamente OpenAI Immagini 2. Le immagini restano visibili in anteprima prima della tua approvazione.'],
  ['Pubblica lo stesso testo su tutti i social?', 'No. Un concept può produrre varianti diverse per tono, formato e obiettivo di ciascuna piattaforma, oppure essere escluso da un canale non adatto.'],
  ['Funziona con più attività?', 'Sì. Puoi creare profili o attività indipendenti. Ogni profilo mantiene separati brand, sito, settore, social, contenuti, calendario, metriche e apprendimento.'],
  ['Come studia il mio brand?', 'Analizza il sito pagina per pagina, non soltanto la homepage, e organizza le informazioni che trovi in un profilo del brand che puoi verificare e correggere.'],
  ['Posso modificare un contenuto?', 'Sì. Copy, visuale, asset e programmazione restano modificabili prima della tua decisione finale. Una modifica rilevante riporta il contenuto nel flusso di approvazione.'],
  ['Quali piattaforme sono previste?', 'Instagram, Facebook, LinkedIn e Google Business Profile. Le funzioni che dipendono da API non ancora collegate restano esplicitamente non disponibili o da configurare.'],
  ['Come usa le metriche?', 'Usa soltanto metriche realmente ricevute dai provider collegati. Non inventa reach, engagement o risultati; i dati reali alimentano progressivamente strategia, giorni, orari, temi e formati.'],
  ['Posso cancellare il piano?', 'La fase commerciale viene sviluppata solo dopo che la versione personale è stabile e verificata. Finché prezzi, pagamenti e piani non sono pronti, non vengono presentati come funzioni attive.'],
  ['Cosa succede se un post non mi piace?', 'Puoi modificarlo oppure scegliere di non pubblicarlo. Senza una tua approvazione esplicita il contenuto non può entrare in pubblicazione.'],
] as const;

function PublicHeader() {
  return <header className="public-nav-shell"><div className="public-nav"><Link className="public-logo" to="/" aria-label="Post Automatici home"><span className="logo-glyph">P</span><span>Post Automatici</span></Link><nav aria-label="Navigazione sito"><Link to="/come-funziona">Come funziona</Link><Link to="/funzionalita">Funzionalità</Link><Link to="/prezzi">Prezzi</Link><Link to="/faq">FAQ</Link></nav><div className="public-nav-actions"><Link className="nav-login" to="/login">Accedi</Link><Link className="button small" to="/register">Inizia</Link></div></div></header>;
}

function PublicFooter() {
  return <footer className="public-footer"><div><Link className="public-logo" to="/"><span className="logo-glyph">P</span><span>Post Automatici</span></Link><p>Brand, strategia, contenuti, anteprima, approvazione, pubblicazione e analisi nello stesso flusso.</p></div><div><strong>Prodotto</strong><Link to="/come-funziona">Come funziona</Link><Link to="/funzionalita">Funzionalità</Link><Link to="/prezzi">Prezzi</Link></div><div><strong>Risorse</strong><Link to="/faq">FAQ</Link><Link to="/social-media-manager-ai">Social Media Manager AI</Link><Link to="/gestione-social-automatica">Gestione automatica</Link></div><div><strong>Accesso</strong><Link to="/login">Accedi</Link><Link to="/register">Crea account</Link></div></footer>;
}

function ProductStage() {
  return <div className="product-stage" aria-label="Anteprima del flusso del prodotto"><div className="product-window"><div className="product-window-bar"><span/><span/><span/><small>Post Automatici</small></div><div className="product-window-body"><aside><b>P</b><span className="active"/><span/><span/><span/><span/></aside><div className="product-dashboard"><div className="mock-topline"><span>Centro approvazioni</span><small>Profilo attività</small></div><h3>Ogni contenuto passa da qui prima di uscire.</h3><div className="mock-metrics"><div><small>Contenuto</small><b>Preview</b></div><div><small>Decisione</small><b>Tu</b></div><div><small>Pubblicazione</small><b>Dopo OK</b></div></div><div className="mock-workflow"><div><span className="flow-dot done">✓</span><p><b>Brand verificato</b><small>Dati separati per attività</small></p></div><div><span className="flow-dot done">✓</span><p><b>Contenuto preparato</b><small>Variante specifica per piattaforma</small></p></div><div><span className="flow-dot current">3</span><p><b>Anteprima obbligatoria</b><small>Copy e visuale visibili prima dell’uscita</small></p></div><div><span className="flow-dot">4</span><p><b>Tua decisione</b><small>Approva oppure non pubblicare</small></p></div></div></div></div></div><div className="floating-post"><div className="post-photo"><span>Anteprima visuale</span></div><div><small>Instagram · orario programmato</small><strong>Contenuto pronto per la tua verifica.</strong><p>Nessuna pubblicazione senza approvazione.</p><span className="post-status">In attesa della tua decisione</span></div></div><div className="floating-signal signal-one"><span>✓</span><div><b>Anteprima pronta</b><small>Controllo umano richiesto</small></div></div><div className="floating-signal signal-two"><span>↗</span><div><b>Dati reali</b><small>Solo provider collegati</small></div></div></div>;
}

function PublicProductInfo() {
  return <div className="sales-chat"><div className="sales-chat-launcher" aria-label="Informazioni prodotto"><span>?</span><b>Chiedi al prodotto</b></div><div className="sales-chat-panel"><div className="sales-chat-head"><div><strong>Assistente prodotto</strong><small>Da configurare con OpenAI</small></div></div><div className="sales-chat-answer">L’assistente pubblico non viene simulato. Sarà attivato soltanto quando OpenAI sarà collegato realmente al backend di produzione.</div></div></div>;
}

export function LandingPage() {
  const base = typeof window === 'undefined' ? '' : window.location.origin;
  const schema = useMemo(() => softwareSchemas(base), [base]);
  return <div className="public-page"><Seo title="Post Automatici | Il Social Media Manager AI per le tue attività" description="Analizza ogni sito pagina per pagina, crea contenuti con OpenAI, mostra sempre l’anteprima e pubblica sui social soltanto dopo la tua approvazione." path="/" structuredData={schema}/><PublicHeader/><main>
    <section className="marketing-hero"><div className="hero-copy"><div className="hero-kicker"><span className="pulse-dot"/>Dal brand alla pubblicazione, con approvazione umana obbligatoria</div><h1>Il tuo Social Media Manager AI.<br/><span>Crea, pubblica e migliora.</span></h1><p>Post Automatici gestisce profili indipendenti per ogni tua attività, studia il sito pagina per pagina, prepara strategia e contenuti con OpenAI e ti mostra sempre la preview prima di qualsiasi pubblicazione.</p><div className="hero-actions left"><Link className="button large" to="/register">Configura la prima attività <span>→</span></Link><Link className="button secondary large" to="/come-funziona">Guarda come funziona</Link></div><div className="hero-trust"><span>Anteprima sempre obbligatoria</span><span>Decisione dal sito o Telegram</span><span>Nessuna integrazione finta</span></div></div><ProductStage/></section>

    <section className="proof-strip" aria-label="Piattaforme target"><span>Un concept. Decisioni specifiche per canale.</span>{platformLabels.map((platform)=><b key={platform}>{platform}</b>)}</section>

    <section className="marketing-section split-intro"><div><span className="section-label">Il problema</span><h2>Gestire i social non è un compito. È una catena di compiti.</h2></div><p>Brand, idee, copy, immagini, calendario, approvazioni, pubblicazione, analytics e apprendimento devono restare collegati. Post Automatici li riunisce senza nascondere ciò che non è ancora configurato.</p></section>

    <section className="before-after"><div className="before-panel"><span>Prima</span><ul><li>“Cosa pubblico questa settimana?”</li><li>Copy e visuali in strumenti separati</li><li>Testo copiato tra più piattaforme</li><li>Calendario aggiornato a mano</li><li>Dati letti senza una decisione successiva</li></ul></div><div className="after-panel"><span>Dopo</span><h3>Una piattaforma.<br/>Profili realmente separati.</h3><div className="after-flow"><b>Brand</b><i>→</i><b>Strategia</b><i>→</i><b>Contenuti</b><i>→</i><b>Risultati</b></div><p>Ogni attività conserva dati, sito, social, calendario, metriche e apprendimento indipendenti.</p></div></section>

    <section className="marketing-section"><div className="section-heading"><span className="section-label">Analisi del sito</span><h2>Il brand si studia pagina per pagina, non dalla sola homepage.</h2><p>Il crawler segue le pagine rilevanti dello stesso sito, raccoglie evidenze e organizza identità, servizi, target, tono, claim, immagini e informazioni utili. Tu puoi verificare e correggere il profilo prima che venga usato.</p></div><div className="scan-showcase"><div className="url-bar"><span>⌕</span><b>https://sito-attivita.it</b><em>Analizza sito</em></div><div className="scan-body"><div className="scan-list"><div className="done"><span>✓</span><p><b>Homepage</b><small>Identità e posizionamento</small></p></div><div className="done"><span>✓</span><p><b>Servizi</b><small>Offerta e differenziatori</small></p></div><div className="done"><span>✓</span><p><b>Chi siamo</b><small>Storia, persone e tono</small></p></div><div className="done"><span>✓</span><p><b>Pagine interne</b><small>Contenuti e informazioni rilevanti</small></p></div><div className="active"><span>•</span><p><b>Brand pronto da verificare</b><small>Correggi o blocca le informazioni importanti</small></p></div></div><div className="brand-result"><small>Brand profile</small><h3>La tua attività</h3><div className="brand-tags"><span>Identità</span><span>Servizi</span><span>Target</span></div><hr/><p><b>Tono</b><span>Estratto e verificabile</span></p><p><b>Focus</b><span>Basato sulle pagine reali</span></p><p><b>Regola</b><span>Non inventare informazioni</span></p></div></div></div></section>

    <section className="marketing-section"><div className="section-heading"><span className="section-label">Come funziona</span><h2>Dal sito al post pubblicato, senza saltare la tua approvazione.</h2></div><div className="workflow-line">{[['01','Crea un profilo','Ogni attività mantiene dati e apprendimento separati'],['02','Analizza il sito','Scansione pagina per pagina e raccolta evidenze'],['03','Conferma il brand','Correggi e blocca ciò che non deve cambiare'],['04','Collega i social','Solo connessioni API realmente configurate'],['05','Genera strategia e contenuti','OpenAI prepara copy e direzione per canale'],['06','Genera immagini','Solo OpenAI Immagini 2 quando serve una nuova immagine AI'],['07','Guarda la preview','Ogni contenuto deve essere visibile prima dell’uscita'],['08','Decidi tu','Approva dal sito o Telegram, oppure non pubblicare'],['09','Pubblica dopo approvazione','Subito o all’orario programmato'],['10','Impara dai dati reali','Metriche provider migliorano progressivamente le decisioni']].map(([n,title,body])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="marketing-section content-showcase"><div className="showcase-copy"><span className="section-label">Non è cross-posting</span><h2>La stessa idea non deve sembrare copiata e incollata.</h2><p>Ogni piattaforma riceve una variante costruita per il proprio contesto. Formato, copy, CTA e visuale restano verificabili prima della tua decisione.</p><ul className="check-list premium"><li>Post, caroselli, storie e formati supportati dalle API</li><li>Frequenza configurabile per singolo profilo</li><li>Immagini AI generate esclusivamente con OpenAI Immagini 2</li><li>Google Business Profile trattato come canale locale specifico</li></ul></div><div className="variants-board"><div className="concept-chip">Concept · una base, quattro adattamenti</div>{[['IG','Instagram','Visual first · formato e caption dedicati'],['f','Facebook','Contesto e conversazione dedicati'],['in','LinkedIn','Taglio professionale dedicato'],['G','Business Profile','Contenuto locale solo se pertinente']].map(([icon,name,detail],index)=><div className="variant-row" key={name}><span className={`platform-mark platform-${index}`}>{icon}</span><p><b>{name}</b><small>{detail}</small></p><em>Preview</em></div>)}</div></section>

    <section className="marketing-section approval-section"><div className="section-heading"><span className="section-label">Controllo umano obbligatorio</span><h2>Ogni contenuto viene mostrato prima. Poi decidi tu.</h2></div><div className="mode-grid"><div className="mode-card"><div className="mode-top"><span className="mode-icon">✓</span><Badge tone="info">ANTEPRIMA</Badge></div><h3>Copy e visuale prima dell’uscita</h3><p>Puoi controllare il contenuto, modificarlo, cambiare visuale oppure rifiutarlo. Nessun contenuto generato può saltare questo passaggio.</p><div className="mini-approval"><div className="mini-media"/><p><b>Post pronto</b><small>In attesa della tua decisione</small></p><button type="button">Approva</button></div></div><div className="mode-card dark"><div className="mode-top"><span className="mode-icon">↗</span><Badge>DOPO IL TUO OK</Badge></div><h3>Pubblicazione immediata o programmata</h3><p>Dopo l’approvazione esplicita, puoi pubblicare subito oppure lasciare che il sistema invii il contenuto all’orario già programmato.</p><div className="automation-route"><span>Preview</span><i>→</i><span>Tuo OK</span><i>→</i><span>Programmato</span><i>→</i><span>Pubblicato</span></div></div></div></section>

    <section className="marketing-section telegram-showcase"><div><span className="section-label">Approvazione Telegram</span><h2>La stessa decisione può arrivare anche sul telefono.</h2><p>Quando Telegram è configurato realmente, ricevi la preview del contenuto e puoi approvare/pubblicare oppure scegliere di non pubblicare. Il bot non sostituisce la tua decisione.</p></div><div className="phone-frame"><div className="phone-head"><span>P</span><p><b>Post Automatici</b><small>Anteprima pronta</small></p></div><div className="telegram-post"><div className="telegram-image">Preview contenuto</div><p><b>Nuovo contenuto Instagram</b><br/>Controlla copy e visuale prima di decidere.</p><div><button type="button">Approva / pubblica</button><button type="button">Non pubblicare</button></div></div></div></section>

    <section className="marketing-section analytics-showcase"><div className="analytics-panel"><div className="analytics-head"><div><small>Provider collegati</small><h3>Metriche reali, oppure nessun dato.</h3></div><span>Analytics</span></div><div className="analytics-metrics"><div><small>Reach</small><b>Dati provider</b></div><div><small>Engagement</small><b>Dati provider</b></div><div><small>Contenuto migliore</small><b>Solo con evidenza</b></div></div><div className="insight-line"><span>AI</span><p><b>Cosa fare dopo</b><small>Gli insight vengono prodotti soltanto a partire da metriche realmente disponibili e tengono separati evidenza, confidenza e azione consigliata.</small></p></div></div><div className="showcase-copy"><span className="section-label">Apprendimento progressivo</span><h2>I risultati reali servono a migliorare le decisioni successive.</h2><p>Quando le API forniscono dati sufficienti, Post Automatici può migliorare progressivamente strategia, orari, giorni, temi e formati. Se i dati non ci sono, non li inventa.</p><div className="three-questions"><div><b>1</b><span>Come sta andando?</span></div><div><b>2</b><span>Perché?</span></div><div><b>3</b><span>Cosa cambiare dopo?</span></div></div></div></section>

    <section className="marketing-section competitor-showcase"><div><span className="section-label">Intelligence</span><h2>Usa informazioni verificabili per trovare opportunità, non per copiare.</h2><p>Le analisi esterne devono usare fonti consentite e distinguere chiaramente dati disponibili, limiti e assenza di integrazioni. Nessuno scraping o dato viene presentato come live se non lo è.</p></div><div className="competitor-stack"><div><span>A</span><b>Fonte A</b><small>Evidenza disponibile</small></div><div><span>B</span><b>Fonte B</b><small>Evidenza disponibile</small></div><div><span>C</span><b>Fonte C</b><small>Evidenza disponibile</small></div><div className="opportunity"><span>↗</span><p><b>Opportunità da validare</b><small>Una decisione proposta resta distinta dai fatti osservati.</small></p></div></div></section>

    <section className="marketing-section sectors"><div className="section-heading"><span className="section-label">Profili illimitati per uso personale</span><h2>Ogni attività è un ambiente indipendente.</h2></div><div className="sector-cloud">{['Ristorazione','Property management','Consulenza','E-commerce','Palestre','Beauty','Attività locali','Agenzie','Professionisti'].map((sector)=><span key={sector}>{sector}</span>)}</div></section>

    <section className="final-cta"><span className="section-label">Prima il prodotto personale</span><h2>Post Automatici deve funzionare davvero prima di essere venduto.</h2><p>La priorità è rendere completo il flusso personale: profili, brand, sito, OpenAI, immagini, social, preview, approvazioni, calendario, pubblicazione, metriche e apprendimento.</p><div><Link className="button large light" to="/register">Configura un’attività</Link><Link to="/come-funziona">Vedi il workflow →</Link></div></section>
  </main><PublicFooter/><PublicProductInfo/></div>;
}

export function PricingPage() {
  return <div className="public-page"><Seo title="Prezzi | Post Automatici" description="La fase commerciale di Post Automatici viene definita solo dopo la stabilizzazione completa della versione personale." path="/prezzi"/><PublicHeader/><main className="pricing-main marketing-page"><div className="center-heading"><span className="section-label">Fase successiva</span><h1>Prima il prodotto personale. Prezzi e clienti vengono dopo.</h1><p>Pagamenti, piani commerciali, limiti per clienti esterni e SaaS multiutente non vengono presentati come attivi finché la versione personale non è realmente stabile e verificata.</p></div><div className="pricing-grid"><Plan name="Uso personale" eyebrow="Priorità attuale" featured features={['Profili attività indipendenti','Analisi sito pagina per pagina','OpenAI per i contenuti','OpenAI Immagini 2 per immagini AI','Anteprima e approvazione obbligatorie','Social e metriche reali quando collegati']}/><Plan name="Clienti esterni" eyebrow="Solo dopo" features={['Da progettare dopo la versione personale stabile','Pagamenti non ancora attivi','Piani commerciali non ancora definiti','Onboarding clienti da validare']}/><Plan name="SaaS multiutente" eyebrow="Fase futura" features={['Da sviluppare dopo uso personale e clienti','Ruoli e billing da definire','Entitlement commerciali da definire','Nessuna promessa live anticipata']}/></div><div className="pricing-note"><strong>Prezzo da definire.</strong><p>Checkout e fatturazione non vengono attivati finché il prodotto personale non ha superato le verifiche funzionali previste.</p></div></main><PublicFooter/></div>;
}

function Plan({name,eyebrow,features,featured=false}:{name:string;eyebrow:string;features:string[];featured?:boolean}) {
  return <Card className={`plan-card ${featured?'featured-card':''}`}>{featured&&<Badge tone="good">Priorità</Badge>}<span className="plan-eyebrow">{eyebrow}</span><h2>{name}</h2><div className="plan-price">Prezzo da definire</div><ul className="feature-list premium">{features.map((feature)=><li key={feature}>{feature}</li>)}</ul><Link className={`button full ${featured?'':'secondary'}`} to="/register">Apri il prodotto</Link></Card>;
}

export function HowItWorksPage() {
  return <MarketingArticle path="/come-funziona" title="Come funziona Post Automatici" description="Il workflow personale completo: attività separate, sito pagina per pagina, OpenAI, anteprima obbligatoria, approvazione, social, metriche reali e apprendimento."><span className="section-label">Come funziona</span><h1>Un workflow leggibile, dalla singola attività alla pubblicazione approvata.</h1><p className="lead">Non devi fidarti di una scatola nera. Ogni fase produce qualcosa che puoi vedere, verificare o correggere prima del passaggio successivo.</p><div className="article-steps">{[['01','Profilo attività','Crea un ambiente indipendente con brand, sito, social, calendario, metriche e apprendimento separati.'],['02','Analisi del sito','Il crawler analizza le pagine rilevanti dello stesso sito e conserva evidenze verificabili.'],['03','Brand Profile','Confermi identità, servizi, target, tono, regole e informazioni bloccate.'],['04','Strategia','Obiettivi, audience, temi, frequenza, giorni e orari vengono salvati per quel profilo.'],['05','Creazione con OpenAI','Copy e varianti vengono generati usando il contesto reale del profilo.'],['06','Immagini con OpenAI Immagini 2','Ogni nuova immagine generata dall’AI usa esclusivamente OpenAI Immagini 2.'],['07','Anteprima obbligatoria','Ogni contenuto mostra copy e visuale prima della pubblicazione.'],['08','Decisione umana','Approvi dal sito o da Telegram, oppure scegli di non pubblicare.'],['09','Pubblicazione','Solo dopo il tuo OK il contenuto può essere inviato subito o all’orario programmato.'],['10','Apprendimento','Le metriche reali disponibili alimentano progressivamente le decisioni successive.']].map(([n,t,b])=><article key={n}><span>{n}</span><div><h2>{t}</h2><p>{b}</p></div></article>)}</div></MarketingArticle>;
}

export function FeaturesPage() {
  return <MarketingArticle path="/funzionalita" title="Funzionalità | Post Automatici" description="Profili indipendenti, analisi sito pagina per pagina, OpenAI, OpenAI Immagini 2, Approval Center, social publishing, analytics reali e apprendimento."><span className="section-label">Funzionalità</span><h1>Non un generatore di caption. Una control room per il lavoro social.</h1><p className="lead">Le funzioni sono organizzate attorno al ciclo operativo personale: conoscere ogni attività, decidere, produrre, verificare, approvare, distribuire e imparare.</p><div className="feature-editorial-grid">{[['Profili attività','Numero illimitato per uso personale, con dati e apprendimento separati.'],['Website Intelligence','Analisi pagina per pagina, sitemap, pagine interne ed evidenze del sito.'],['Brand Intelligence','Identità, tono, target, servizi, claim e campi verificabili.'],['Strategia editoriale','Pillar, frequenza, giorni, orari, obiettivi e decisioni per piattaforma.'],['Content creation','OpenAI per copy, hook, caption, CTA e varianti per canale.'],['OpenAI Immagini 2','Unico motore ammesso per la generazione di nuove immagini AI.'],['Approval Center','Preview obbligatoria, modifica, approvazione o rifiuto prima della pubblicazione.'],['Telegram approval','Stessa decisione dal telefono quando il bot è realmente configurato.'],['Social Connections','Instagram, Facebook, LinkedIn e Google Business Profile, senza connessioni finte.'],['Analytics & Learning','Solo metriche reali dei provider per migliorare progressivamente strategia e calendario.']].map(([t,b])=><article key={t}><span>↗</span><h2>{t}</h2><p>{b}</p></article>)}</div></MarketingArticle>;
}

export function FaqPage() {
  const schema = useMemo(()=>({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqItems.map(([question,answer])=>({'@type':'Question',name:question,acceptedAnswer:{'@type':'Answer',text:answer}}))}),[]);
  return <div className="public-page"><Seo title="FAQ | Post Automatici" description="Risposte su approvazione obbligatoria, OpenAI Immagini 2, profili indipendenti, social, analisi del sito e metriche reali." path="/faq" structuredData={schema}/><PublicHeader/><main className="marketing-page faq-page"><div className="center-heading"><span className="section-label">FAQ</span><h1>Domande prima di affidare il workflow alla piattaforma.</h1><p>Le risposte distinguono ciò che il prodotto fa realmente da ciò che dipende ancora da API o credenziali da configurare.</p></div><div className="faq-list">{faqItems.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></main><PublicFooter/></div>;
}

export function SocialMediaManagerAiPage() {
  return <MarketingArticle path="/social-media-manager-ai" title="Social Media Manager AI | Post Automatici" description="Un Social Media Manager AI completo conosce il brand, genera con OpenAI, mostra la preview, pubblica dopo approvazione e impara da dati reali."><span className="section-label">Social Media Manager AI</span><h1>Un Social Media Manager AI serve solo se gestisce il processo, non una singola casella di testo.</h1><p className="lead">Generare una caption è facile. Mantenere coerenza di brand, scegliere il formato corretto, mostrare l’anteprima, rispettare l’approvazione umana e imparare dai risultati reali è il lavoro che rende utile l’automazione.</p><div className="article-two-col"><div><h2>Cosa deve fare</h2><ul className="check-list premium"><li>Conoscere ogni attività prima di scrivere</li><li>Analizzare il sito pagina per pagina</li><li>Separare le logiche per piattaforma</li><li>Mostrare sempre preview prima della pubblicazione</li><li>Usare OpenAI Immagini 2 per le immagini AI</li><li>Collegare metriche reali e decisioni successive</li></ul></div><div><h2>Cosa non deve fare</h2><ul className="cross-list"><li>Inventare fatti o risultati</li><li>Pubblicare senza approvazione umana</li><li>Fingere connessioni API</li><li>Usare dati di altri profili</li><li>Ottimizzare senza evidenza sufficiente</li></ul></div></div></MarketingArticle>;
}

export function AutomaticSocialManagementPage() {
  return <MarketingArticle path="/gestione-social-automatica" title="Gestione social automatica con controllo | Post Automatici" description="Automazione dopo approvazione: ogni contenuto viene mostrato prima e può essere pubblicato automaticamente soltanto dopo il tuo OK."><span className="section-label">Gestione social automatica</span><h1>Automazione non significa perdere il controllo.</h1><p className="lead">In Post Automatici l’automazione riguarda ciò che accade dopo la tua decisione: ogni contenuto viene mostrato in anteprima e richiede sempre una tua approvazione esplicita. Solo dopo può essere pubblicato subito o automaticamente all’orario programmato.</p><div className="mode-grid article-modes"><div className="mode-card"><Badge tone="info">1 · PREVIEW</Badge><h2>Controllo prima dell’uscita</h2><p>Copy e visuale vengono mostrati nel sito e, quando configurato, anche su Telegram.</p></div><div className="mode-card dark"><Badge>2 · DOPO APPROVAZIONE</Badge><h2>Continuità operativa</h2><p>Dopo il tuo OK, il job può pubblicare all’orario scelto. Senza il tuo OK il contenuto resta fermo.</p></div></div></MarketingArticle>;
}

function MarketingArticle({path,title,description,children}:{path:string;title:string;description:string;children:React.ReactNode}) {
  return <div className="public-page"><Seo title={title} description={description} path={path}/><PublicHeader/><main className="marketing-article">{children}<div className="article-cta"><h2>Vuoi vedere il flusso nel prodotto?</h2><p>Configura una tua attività e parti dal profilo del brand.</p><Link className="button" to="/register">Inizia</Link></div></main><PublicFooter/></div>;
}
