import { useMemo, useState } from 'react';
import { Link } from 'react-router';
import { Badge, Card } from '../components/ui';
import { Seo, softwareSchemas } from '../components/Seo';
import { useLocalE2E } from '../services/local-e2e';

const platformLabels = ['Instagram', 'Facebook', 'LinkedIn', 'Google Business Profile'];
const faqItems = [
  ['Devo collegare i miei social?', 'Sì, per pubblicare è necessario autorizzare gli account che vuoi gestire. Puoi comunque preparare strategia e contenuti prima del collegamento.'],
  ['Posso approvare i post prima che escano?', 'Sì. Ogni canale può lavorare in modalità manuale oppure automatica, così mantieni il livello di controllo che preferisci.'],
  ['Crea anche le immagini?', 'Il prodotto è progettato per usare prima di tutto foto e asset reali del brand e, quando previsto dal piano e dal flusso, può ricorrere alla generazione visuale.'],
  ['Pubblica lo stesso testo su tutti i social?', 'No. Un concept può diventare varianti diverse per tono, formato e obiettivo di ciascuna piattaforma, oppure essere escluso da un canale non adatto.'],
  ['Funziona con qualsiasi settore?', 'L’architettura è generalista: parte dal brand, dal pubblico e dagli obiettivi. Non usa una strategia rigida uguale per ogni attività.'],
  ['Come studia il mio brand?', 'Parte dal sito e dai dati che confermi, organizza identità, servizi, target, tono e regole del brand e mantiene i campi che decidi di bloccare.'],
  ['Posso modificare un contenuto?', 'Sì. Copy, visuale, asset, programmazione e approvazione restano modificabili nei punti previsti dal workflow.'],
  ['Quali piattaforme sono previste?', 'La base applicativa è predisposta per Facebook, Instagram, LinkedIn e Google Business Profile. La validazione live richiede le credenziali ufficiali dei provider.'],
  ['Posso cancellare il piano?', 'La gestione commerciale definitiva dipenderà dai piani pubblicati al lancio. Non mostriamo condizioni o prezzi non ancora approvati.'],
  ['Cosa succede se un post non mi piace?', 'Puoi modificarlo, cambiare la grafica o la foto, oppure rifiutarlo. Il contenuto non deve essere accettato per forza.'],
] as const;

function PublicHeader() {
  return <header className="public-nav-shell"><div className="public-nav"><Link className="public-logo" to="/" aria-label="SocialPilot AI home"><span className="logo-glyph">S</span><span>SocialPilot AI</span></Link><nav aria-label="Navigazione sito"><Link to="/come-funziona">Come funziona</Link><Link to="/funzionalita">Funzionalità</Link><Link to="/prezzi">Prezzi</Link><Link to="/faq">FAQ</Link></nav><div className="public-nav-actions"><Link className="nav-login" to="/login">Accedi</Link><Link className="button small" to="/register">Inizia</Link></div></div></header>;
}

function PublicFooter() {
  return <footer className="public-footer"><div><Link className="public-logo" to="/"><span className="logo-glyph">S</span><span>SocialPilot AI</span></Link><p>Strategia, contenuti, approvazione, pubblicazione e analisi in un unico flusso.</p></div><div><strong>Prodotto</strong><Link to="/come-funziona">Come funziona</Link><Link to="/funzionalita">Funzionalità</Link><Link to="/prezzi">Prezzi</Link></div><div><strong>Risorse</strong><Link to="/faq">FAQ</Link><Link to="/social-media-manager-ai">Social Media Manager AI</Link><Link to="/gestione-social-automatica">Gestione automatica</Link></div><div><strong>Accesso</strong><Link to="/login">Accedi</Link><Link to="/register">Crea account</Link></div></footer>;
}

function ProductStage() {
  return <div className="product-stage" aria-label="Anteprima del prodotto"><div className="product-window"><div className="product-window-bar"><span/><span/><span/><small>Control room</small></div><div className="product-window-body"><aside><b>S</b><span className="active"/><span/><span/><span/><span/></aside><div className="product-dashboard"><div className="mock-topline"><span>Oggi</span><small>Workspace</small></div><h3>Tutto ciò che richiede attenzione.</h3><div className="mock-metrics"><div><small>Da approvare</small><b>4</b></div><div><small>Programmato</small><b>12</b></div><div><small>Connessioni</small><b>4/4</b></div></div><div className="mock-workflow"><div><span className="flow-dot done">✓</span><p><b>Brand analizzato</b><small>Identità e tono confermati</small></p></div><div><span className="flow-dot done">✓</span><p><b>Post creato</b><small>Varianti per piattaforma</small></p></div><div><span className="flow-dot current">3</span><p><b>In approvazione</b><small>Pronto in pochi secondi</small></p></div><div><span className="flow-dot">4</span><p><b>Programmato</b><small>Pubblicazione controllata</small></p></div></div></div></div></div><div className="floating-post"><div className="post-photo"><span>Visual del brand</span></div><div><small>Instagram · oggi 18:30</small><strong>Una variante pensata per il canale.</strong><p>Copy, CTA e visuale restano controllabili.</p><span className="post-status">Pronto da approvare</span></div></div><div className="floating-signal signal-one"><span>✓</span><div><b>Post creato</b><small>Quality gate superato</small></div></div><div className="floating-signal signal-two"><span>↗</span><div><b>Performance</b><small>Insight pronto</small></div></div></div>;
}

function PublicChat() {
  const local = useLocalE2E();
  const [question, setQuestion] = useState('Posso approvare i post prima della pubblicazione?');
  const [answer, setAnswer] = useState('');
  const [citations, setCitations] = useState<string[]>([]);
  const [open, setOpen] = useState(false);
  const ask = async () => {
    if (!local.enabled) {
      setAnswer('Sì. Il flusso prevede approvazione manuale per singola piattaforma oppure automazione, in base alle impostazioni del workspace.');
      setCitations([]);
      return;
    }
    const result = await local.api<{answer:string;citations:string[]}>('/chat/public', { method: 'POST', body: JSON.stringify({ message: question }) });
    setAnswer(result.answer);
    setCitations(result.citations);
  };
  return <div className={`sales-chat ${open ? 'open' : ''}`}><button className="sales-chat-launcher" type="button" aria-expanded={open} onClick={() => setOpen((value) => !value)}><span>?</span><b>Chiedi al prodotto</b></button>{open&&<div className="sales-chat-panel"><div className="sales-chat-head"><div><strong>Assistente prodotto</strong><small>Domande su funzioni e workflow</small></div><button type="button" aria-label="Chiudi assistente" onClick={()=>setOpen(false)}>×</button></div><div className="quick-questions"><button type="button" onClick={()=>setQuestion('Posso approvare i post prima della pubblicazione?')}>Posso approvare prima?</button><button type="button" onClick={()=>setQuestion('Usa lo stesso testo su tutti i social?')}>Adatta i post ai canali?</button></div><label>La tua domanda<input data-testid="public-chat-input" aria-label="Domanda al chatbot" value={question} onChange={(event)=>setQuestion(event.target.value)}/></label><button data-testid="public-chat-send" className="button full" type="button" onClick={()=>void ask()}>Chiedi</button>{answer&&<div className="sales-chat-answer" data-testid="public-chat-answer">{answer}</div>}{citations.length>0&&<small>Fonti: {citations.join(', ')}</small>}</div>}</div>;
}

export function LandingPage() {
  const base = typeof window === 'undefined' ? '' : window.location.origin;
  const schema = useMemo(() => softwareSchemas(base), [base]);
  return <div className="public-page"><Seo title="SocialPilot AI | Il Social Media Manager AI per il tuo brand" description="Analizza il brand, crea contenuti distinti per piattaforma, li fa approvare o li automatizza e trasforma i risultati in decisioni." path="/" structuredData={schema}/><PublicHeader/><main>
    <section className="marketing-hero"><div className="hero-copy"><div className="hero-kicker"><span className="pulse-dot"/>Dal brand alla pubblicazione, in un solo flusso</div><h1>Il tuo Social Media Manager AI.<br/><span>Crea, pubblica e migliora.</span></h1><p>Trasforma sito, identità e obiettivi in una presenza social coerente. La piattaforma prepara contenuti specifici per ogni canale, ti lascia approvare ciò che vuoi e usa i risultati per suggerire cosa fare dopo.</p><div className="hero-actions left"><Link className="button large" to="/register">Inizia a configurare il brand <span>→</span></Link><Link className="button secondary large" to="/come-funziona">Guarda come funziona</Link></div><div className="hero-trust"><span>Controllo umano quando vuoi</span><span>Varianti native per canale</span><span>Nessun cliente o risultato inventato</span></div></div><ProductStage/></section>

    <section className="proof-strip" aria-label="Piattaforme previste"><span>Un concept. Quattro decisioni diverse.</span>{platformLabels.map((platform)=><b key={platform}>{platform}</b>)}</section>

    <section className="marketing-section split-intro"><div><span className="section-label">Il problema</span><h2>Gestire i social non è un compito. È una catena di compiti.</h2></div><p>Idee, copy, grafiche, calendario, approvazioni, pubblicazione, analytics e competitor finiscono spesso in strumenti diversi. Il costo reale è il tempo perso a tenere tutto insieme.</p></section>

    <section className="before-after"><div className="before-panel"><span>Prima</span><ul><li>“Cosa pubblico questa settimana?”</li><li>Copy e visuali in strumenti separati</li><li>Testo copiato tra più piattaforme</li><li>Calendario aggiornato a mano</li><li>Dati letti senza una decisione successiva</li></ul></div><div className="after-panel"><span>Dopo</span><h3>Una piattaforma.<br/>Un workflow continuo.</h3><div className="after-flow"><b>Brand</b><i>→</i><b>Strategia</b><i>→</i><b>Contenuti</b><i>→</i><b>Risultati</b></div><p>Ogni passaggio alimenta quello successivo senza toglierti il controllo.</p></div></section>

    <section className="marketing-section"><div className="section-heading"><span className="section-label">Website analysis</span><h2>Inizia da ciò che il tuo brand dice già.</h2><p>Inserisci il sito. Il sistema organizza le informazioni rilevanti e ti mostra cosa ha capito prima di usarlo nei contenuti.</p></div><div className="scan-showcase"><div className="url-bar"><span>⌕</span><b>www.pizzeriaexample.it</b><em>Analizza brand</em></div><div className="scan-body"><div className="scan-list"><div className="done"><span>✓</span><p><b>Identità rilevata</b><small>Nome, settore, posizionamento</small></p></div><div className="done"><span>✓</span><p><b>Servizi identificati</b><small>Offerta e differenziatori</small></p></div><div className="done"><span>✓</span><p><b>Tono analizzato</b><small>Vocabolario e stile comunicativo</small></p></div><div className="done"><span>✓</span><p><b>Target organizzato</b><small>Pubblico e bisogni principali</small></p></div><div className="active"><span>•</span><p><b>Brand pronto da confermare</b><small>Correggi o blocca le informazioni importanti</small></p></div></div><div className="brand-result"><small>Brand profile</small><h3>Forno Example</h3><div className="brand-tags"><span>Locale</span><span>Artigianale</span><span>Conviviale</span></div><hr/><p><b>Tono</b><span>Diretto, caldo, concreto</span></p><p><b>Focus</b><span>Prodotto, persone, territorio</span></p><p><b>Regola</b><span>Mai inventare promozioni</span></p></div></div></div></section>

    <section className="marketing-section"><div className="section-heading"><span className="section-label">Come funziona</span><h2>Dal sito al post pubblicato, senza nascondere i passaggi.</h2></div><div className="workflow-line">{[['01','Inserisci il sito','Raccogli le basi del brand'],['02','Conferma l’identità','Blocca ciò che non deve cambiare'],['03','Collega i canali','Scegli account e modalità'],['04','Genera la strategia','Pillar, obiettivi e calendario'],['05','Crea i contenuti','Copy e visuali per canale'],['06','Approva o automatizza','Controllo dove ti serve'],['07','Pubblica','Account e formato corretti'],['08','Impara','Insight dai risultati disponibili']].map(([n,title,body])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="marketing-section content-showcase"><div className="showcase-copy"><span className="section-label">Non è cross-posting</span><h2>La stessa idea non deve sembrare copiata e incollata.</h2><p>Ogni piattaforma riceve una decisione: variante nativa, concept separato oppure nessun post se il contenuto non è adatto.</p><ul className="check-list premium"><li>Hook e lunghezza coerenti con il canale</li><li>CTA e hashtag modificabili</li><li>Formato validato prima della pubblicazione</li><li>Google Business Profile trattato come contesto locale</li></ul></div><div className="variants-board"><div className="concept-chip">Concept · Dietro le quinte del prodotto</div>{[['IG','Instagram','Visual first · caption più narrativa'],['f','Facebook','Contesto più completo · conversazione'],['in','LinkedIn','Insight professionale · niente copia IG'],['G','Business Profile','Contenuto locale solo se pertinente']].map(([icon,name,detail],index)=><div className="variant-row" key={name}><span className={`platform-mark platform-${index}`}>{icon}</span><p><b>{name}</b><small>{detail}</small></p><em>{index===3?'Valuta':'Pronto'}</em></div>)}</div></section>

    <section className="marketing-section approval-section"><div className="section-heading"><span className="section-label">Il livello di controllo lo scegli tu</span><h2>Approva in 10 secondi. Oppure lascia lavorare l’automazione.</h2></div><div className="mode-grid"><div className="mode-card"><div className="mode-top"><span className="mode-icon">✓</span><Badge tone="info">MANUALE</Badge></div><h3>Vuoi vedere tutto prima?</h3><p>Apri il contenuto, modifica copy o visuale, scegli una foto diversa e approva quando è pronto.</p><div className="mini-approval"><div className="mini-media"/><p><b>Post pronto</b><small>Instagram · 18:30</small></p><button type="button">Approva</button></div></div><div className="mode-card dark"><div className="mode-top"><span className="mode-icon">↗</span><Badge>AUTO</Badge></div><h3>Vuoi togliere lavoro ripetitivo?</h3><p>Imposta i canali idonei in automatico. Quality gate, account e stato restano tracciati nel workflow.</p><div className="automation-route"><span>Pronto</span><i>→</i><span>Validato</span><i>→</i><span>Programmato</span><i>→</i><span>Pubblicato</span></div></div></div></section>

    <section className="marketing-section telegram-showcase"><div><span className="section-label">Approvazione rapida</span><h2>Non devi aprire il pannello ogni volta.</h2><p>Il flusso Telegram previsto porta l’approvazione dove sei già: ricevi il post, decidi, continui la giornata.</p></div><div className="phone-frame"><div className="phone-head"><span>S</span><p><b>SocialPilot AI</b><small>Post pronto</small></p></div><div className="telegram-post"><div className="telegram-image">Preview contenuto</div><p><b>Nuovo post Instagram</b><br/>“Una storia dal dietro le quinte del tuo brand…”</p><div><button type="button">Approva</button><button type="button">Modifica</button><button type="button">Rifiuta</button></div></div></div></section>

    <section className="marketing-section analytics-showcase"><div className="analytics-panel"><div className="analytics-head"><div><small>Ultimi 30 giorni</small><h3>Come sta andando?</h3></div><span>Overview</span></div><div className="analytics-metrics"><div><small>Reach</small><b>+18%</b></div><div><small>Engagement</small><b>4,8%</b></div><div><small>Contenuto migliore</small><b>Behind the scenes</b></div></div><div className="chart-bars" aria-hidden="true"><span style={{height:'34%'}}/><span style={{height:'48%'}}/><span style={{height:'42%'}}/><span style={{height:'67%'}}/><span style={{height:'58%'}}/><span style={{height:'82%'}}/><span style={{height:'75%'}}/><span style={{height:'92%'}}/></div><div className="insight-line"><span>AI</span><p><b>Cosa fare adesso</b><small>I contenuti dietro le quinte stanno ottenendo più interazioni nel mock dimostrativo. Mantieni il test e verifica su un campione reale.</small></p></div></div><div className="showcase-copy"><span className="section-label">Analytics che portano a una decisione</span><h2>Non si limita a mostrare grafici. Ti dice cosa osservare dopo.</h2><p>Le metriche dipendono da ciò che ogni provider rende disponibile. Gli insight separano evidenza, confidenza e azione consigliata.</p><div className="three-questions"><div><b>1</b><span>Come sta andando?</span></div><div><b>2</b><span>Perché?</span></div><div><b>3</b><span>Cosa faccio adesso?</span></div></div></div></section>

    <section className="marketing-section competitor-showcase"><div><span className="section-label">Competitor intelligence</span><h2>Guarda il mercato per trovare spazio, non per copiare.</h2><p>La piattaforma è predisposta per confrontare temi, posizionamento e opportunità usando fonti consentite. Nessuna promessa di scraping indiscriminato.</p></div><div className="competitor-stack"><div><span>A</span><b>Competitor A</b><small>Prodotto · promozioni</small></div><div><span>B</span><b>Competitor B</b><small>Education · community</small></div><div><span>C</span><b>Competitor C</b><small>Authority · casi pratici</small></div><div className="opportunity"><span>↗</span><p><b>Opportunità individuata</b><small>Un territorio editoriale meno presidiato da validare.</small></p></div></div></section>

    <section className="marketing-section sectors"><div className="section-heading"><span className="section-label">Un motore, brand diversi</span><h2>Parte dalle regole dell’attività, non da un template di settore.</h2></div><div className="sector-cloud">{['Ristoranti','Pizzerie','Property manager','Networker','Consulenti','Professionisti','E-commerce','Palestre','Beauty','Attività locali','Agenzie'].map((sector)=><span key={sector}>{sector}</span>)}</div></section>

    <section className="final-cta"><span className="section-label">Meno strumenti. Più continuità.</span><h2>Costruisci il sistema che gestisce i social insieme a te.</h2><p>Configura il brand, scegli il livello di controllo e porta strategia, contenuti e risultati nello stesso posto.</p><div><Link className="button large light" to="/register">Inizia la configurazione</Link><Link to="/prezzi">Confronta i piani →</Link></div></section>
  </main><PublicFooter/><PublicChat/></div>;
}

export function PricingPage() {
  return <div className="public-page"><Seo title="Prezzi | SocialPilot AI" description="Confronta i livelli di prodotto per contenuti, piattaforme, automazione, analytics, storage e team senza prezzi o limiti inventati." path="/prezzi"/><PublicHeader/><main className="pricing-main marketing-page"><div className="center-heading"><span className="section-label">Piani</span><h1>Scegli il livello di automazione, non una lista infinita di feature.</h1><p>I prezzi commerciali non sono ancora pubblicati. Le capacità sottostanti sono configurabili e gli entitlement vengono verificati anche server-side.</p></div><div className="pricing-grid"><Plan name="Starter" eyebrow="Per iniziare" features={['Piano editoriale configurabile','Piattaforme incluse dal piano','Approvazione manuale','Asset Library','Analytics essenziali']}/><Plan name="Growth" eyebrow="Più automazione" featured features={['Tutto in Starter','Auto-publishing quando incluso','Analytics più avanzati','Competitor refresh configurabile','Generazione immagini quando inclusa']}/><Plan name="Pro" eyebrow="Più capacità" features={['Tutto in Growth','Quote e storage maggiori','Più utenti quando previsti','Funzioni premium configurabili','Controlli e supporto estesi']}/></div><div className="pricing-note"><strong>Nessun prezzo fittizio.</strong><p>Checkout e fatturazione live non sono ancora attivi in questa fase. Il sito non mostra importi finché non vengono approvati e configurati.</p></div></main><PublicFooter/></div>;
}

function Plan({name,eyebrow,features,featured=false}:{name:string;eyebrow:string;features:string[];featured?:boolean}) {
  return <Card className={`plan-card ${featured?'featured-card':''}`}>{featured&&<Badge tone="good">Consigliato quando configurato</Badge>}<span className="plan-eyebrow">{eyebrow}</span><h2>{name}</h2><div className="plan-price">Prezzo da definire</div><ul className="feature-list premium">{features.map((feature)=><li key={feature}>{feature}</li>)}</ul><Link className={`button full ${featured?'':'secondary'}`} to="/register">Configura il workspace</Link></Card>;
}

export function HowItWorksPage() {
  return <MarketingArticle path="/come-funziona" title="Come funziona SocialPilot AI" description="Dal sito al calendario editoriale, dall’approvazione alla pubblicazione: il workflow completo del Social Media Manager AI."><span className="section-label">Come funziona</span><h1>Un workflow leggibile, dall’identità del brand al prossimo contenuto.</h1><p className="lead">Non devi fidarti di una scatola nera. Ogni fase produce qualcosa che puoi vedere, confermare e usare nella fase successiva.</p><div className="article-steps">{[['01','Analisi del brand','Il sito e i dati confermati diventano un Brand Profile strutturato.'],['02','Strategia','Obiettivi, audience e pillar vengono organizzati in una strategia editoriale.'],['03','Pianificazione','Il calendario assegna tema, piattaforma, formato e momento di pubblicazione.'],['04','Creazione','Ogni concept produce varianti coerenti con il canale e una direzione visuale.'],['05','Controllo qualità','Regole di brand, fatti, duplicazione e compatibilità vengono verificate prima dell’uscita.'],['06','Approvazione','Puoi approvare, modificare, cambiare visuale o rifiutare.'],['07','Pubblicazione','Il job usa l’account associato e il payload validato per la piattaforma.'],['08','Apprendimento','Le metriche realmente disponibili alimentano insight e prossime decisioni.']].map(([n,t,b])=><article key={n}><span>{n}</span><div><h2>{t}</h2><p>{b}</p></div></article>)}</div></MarketingArticle>;
}

export function FeaturesPage() {
  return <MarketingArticle path="/funzionalita" title="Funzionalità | SocialPilot AI" description="Brand intelligence, strategia, content creation, Approval Center, Asset Library, publishing, analytics e connection health in un unico SaaS."><span className="section-label">Funzionalità</span><h1>Non un generatore di caption. Una control room per il lavoro social.</h1><p className="lead">Le funzioni sono organizzate attorno al ciclo operativo: capire il brand, decidere cosa pubblicare, produrre, controllare, distribuire e imparare.</p><div className="feature-editorial-grid">{[['Brand Intelligence','Identità, tono, target, servizi, claim e campi bloccabili.'],['Strategia editoriale','Pillar, mix di contenuti, obiettivi e decisioni per piattaforma.'],['Calendario','Viste operative per capire cosa esce, dove e in quale stato.'],['Content creation','Hook, caption, CTA, hashtag e visual brief distinti per canale.'],['Approval Center','Approva, modifica, cambia grafica, scegli foto o rifiuta.'],['Asset Library','Foto, loghi e documenti con ricerca, tag, preferiti e stato.'],['Social Connections','Connessioni e account separati, health e azioni di riconnessione.'],['Analytics & Learning','Metriche disponibili, insight, confidenza ed evidenza.'],['Plan entitlements','Quote e feature protette anche lato server, non solo nella UI.']].map(([t,b])=><article key={t}><span>↗</span><h2>{t}</h2><p>{b}</p></article>)}</div></MarketingArticle>;
}

export function FaqPage() {
  const schema = useMemo(()=>({'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqItems.map(([question,answer])=>({'@type':'Question',name:question,acceptedAnswer:{'@type':'Answer',text:answer}}))}),[]);
  return <div className="public-page"><Seo title="FAQ | SocialPilot AI" description="Risposte su approvazione, automazione, immagini, piattaforme, analisi del brand e modifica dei contenuti." path="/faq" structuredData={schema}/><PublicHeader/><main className="marketing-page faq-page"><div className="center-heading"><span className="section-label">FAQ</span><h1>Domande prima di affidare il workflow alla piattaforma.</h1><p>Le risposte distinguono ciò che il prodotto è progettato per fare da ciò che richiede ancora validazione live dei provider.</p></div><div className="faq-list">{faqItems.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></main><PublicFooter/></div>;
}

export function SocialMediaManagerAiPage() {
  return <MarketingArticle path="/social-media-manager-ai" title="Social Media Manager AI | Strategia, contenuti e controllo" description="Cos’è un Social Media Manager AI e perché il valore nasce dal workflow completo, non dalla sola generazione di testi."><span className="section-label">Social Media Manager AI</span><h1>Un Social Media Manager AI serve solo se gestisce il processo, non una singola casella di testo.</h1><p className="lead">Generare una caption è facile. Mantenere coerenza di brand, decidere il formato corretto, usare gli asset giusti, rispettare approvazioni e imparare dai risultati è il lavoro che rende utile l’automazione.</p><div className="article-two-col"><div><h2>Cosa dovrebbe fare</h2><ul className="check-list premium"><li>Conoscere il brand prima di scrivere</li><li>Separare le logiche per piattaforma</li><li>Lasciare una vera possibilità di controllo</li><li>Validare prima della pubblicazione</li><li>Collegare analytics e decisioni successive</li></ul></div><div><h2>Cosa non dovrebbe fare</h2><ul className="cross-list"><li>Inventare fatti o risultati</li><li>Pubblicare lo stesso testo ovunque</li><li>Nascondere errori di connessione</li><li>Usare dati di altri tenant</li><li>Ottimizzare senza evidenza sufficiente</li></ul></div></div></MarketingArticle>;
}

export function AutomaticSocialManagementPage() {
  return <MarketingArticle path="/gestione-social-automatica" title="Gestione social automatica con controllo | SocialPilot AI" description="Automatizza creazione e pubblicazione dei contenuti mantenendo approvazioni, quality gate, quote e connection health."><span className="section-label">Gestione social automatica</span><h1>Automazione non significa perdere il controllo.</h1><p className="lead">La modalità corretta è scegliere cosa può procedere da solo e cosa deve fermarsi per una decisione umana. Le due modalità possono convivere nello stesso workspace.</p><div className="mode-grid article-modes"><div className="mode-card"><Badge tone="info">MANUALE</Badge><h2>Controllo prima dell’uscita</h2><p>Utile per brand sensibili, campagne importanti o canali che vuoi supervisionare personalmente.</p></div><div className="mode-card dark"><Badge>AUTO</Badge><h2>Continuità operativa</h2><p>Utile dove account, formato, autorizzazioni e quality gate sono già in uno stato valido.</p></div></div></MarketingArticle>;
}

function MarketingArticle({path,title,description,children}:{path:string;title:string;description:string;children:React.ReactNode}) {
  return <div className="public-page"><Seo title={title} description={description} path={path}/><PublicHeader/><main className="marketing-article">{children}<div className="article-cta"><h2>Vuoi vedere il flusso nel prodotto?</h2><p>Configura un workspace e parti dal Brand Profile.</p><Link className="button" to="/register">Inizia</Link></div></main><PublicFooter/></div>;
}
