import { useState } from 'react';
import { Link } from 'react-router';
import { Card, Badge } from '../components/ui';
import { useLocalE2E } from '../services/local-e2e';

export function LandingPage() {
  const local=useLocalE2E();const [question,setQuestion]=useState('Come funziona la sicurezza multi-tenant?');const [answer,setAnswer]=useState('');const [citations,setCitations]=useState<string[]>([]);
  const ask=async()=>{if(!local.enabled){setAnswer('Modalità mock: configura VITE_LOCAL_API_URL per interrogare la knowledge base locale.');return;}const result=await local.api<{answer:string;citations:string[]}>('/chat/public',{method:'POST',body:JSON.stringify({message:question})});setAnswer(result.answer);setCitations(result.citations)};
  return <div className="public-page"><header className="public-nav"><Link className="public-logo" to="/">SocialPilot AI</Link><nav><Link to="/pricing">Piani</Link><Link to="/app">Prodotto</Link><Link to="/login">Accedi</Link><Link className="button small" to="/register">Crea account</Link></nav></header><main><section className="hero"><Badge tone="info">AI social media manager con controllo umano</Badge><h1>Strategia, contenuti, approvazioni e pubblicazione in un unico sistema.</h1><p>Analizza il brand, pianifica il calendario editoriale, adatta ogni idea al canale corretto e misura ciò che funziona. Il local E2E usa Supabase Docker e provider mock; nessuna API social reale è collegata.</p><div className="hero-actions"><Link className="button" to="/register">Avvia E2E locale</Link><Link className="button secondary" to="/pricing">Vedi i piani</Link></div></section><section className="public-grid three"><Card><h3>Capisce il brand</h3><p>Website scan, Brand Profile versionato, claim, target, tono e lock.</p></Card><Card><h3>Decide per canale</h3><p>Instagram, Facebook, LinkedIn e Google Business Profile ricevono varianti native, concept separati o skip.</p></Card><Card><h3>Automazione controllata</h3><p>AUTO/MANUALE per piattaforma, quality gate, anti-duplicate, scheduler idempotente e learning.</p></Card></section><section className="section-band"><div><span className="eyebrow">Flusso</span><h2>Dal sito del cliente al post pubblicato mock.</h2></div><div className="steps-inline">{['Onboarding','Brand intelligence','Strategia','Calendario','Concept','Varianti','QA','Approval','Publishing','Analytics','Learning'].map((step,i)=><span key={step}><b>{i+1}</b>{step}</span>)}</div></section></main><details className="chat-widget" open><summary>Assistente prodotto</summary><div><strong>Chatbot pubblico · knowledge commerciale</strong><p>Non riceve tenantId né token tenant.</p><input data-testid="public-chat-input" aria-label="Domanda al chatbot" value={question} onChange={(e)=>setQuestion(e.target.value)}/><button data-testid="public-chat-send" className="button small" onClick={()=>void ask()}>Chiedi</button>{answer&&<p data-testid="public-chat-answer">{answer}</p>}{citations.length>0&&<small>Fonti locali: {citations.join(', ')}</small>}</div></details></div>;
}

export function PricingPage(){return <div className="public-page"><header className="public-nav"><Link className="public-logo" to="/">SocialPilot AI</Link><nav><Link to="/">Home</Link><Link to="/login">Accedi</Link><Link className="button small" to="/register">Crea account</Link></nav></header><main className="pricing-main"><div className="center-heading"><span className="eyebrow">Piani configurabili</span><h1>Costi infrastrutturali proporzionati ai ricavi.</h1><p>Nessun checkout è attivo: il piano local-dev è una fixture €0.</p></div><div className="public-grid three"><Plan name="Starter" price="€—" features={['1 brand','Frequenza configurabile','Canali configurabili','Approvazione manuale']}/><Plan name="Growth" price="€—" featured features={['AUTO/MANUALE per canale','Analytics','Google Business Profile','Learning']}/><Plan name="Agency" price="€—" features={['Multi-brand','Team','Quote personalizzate','Controlli admin']}/></div></main></div>}
function Plan({name,price,features,featured=false}:{name:string;price:string;features:string[];featured?:boolean}){return <Card className={featured?'featured-card':''}>{featured&&<Badge tone="good">Più completo</Badge>}<h2>{name}</h2><div className="plan-price">{price}</div><ul className="feature-list">{features.map((feature)=><li key={feature}>{feature}</li>)}</ul><Link className="button full" to="/register">Crea account locale</Link></Card>}
