import { useMemo, useState } from 'react';
import { Link } from 'react-router';
import { Badge, Card, EmptyState, MetricCard, PageHeader, Progress } from '../components/ui';
import { useSaasRepository, useSaasSnapshot } from '../services/SaasServicesProvider';
import { useLocalE2E } from '../services/local-e2e';

const formatMetric=(value:number)=>new Intl.NumberFormat('it-IT').format(value);

export function AssetsPage(){const {assets}=useSaasSnapshot();return <><PageHeader eyebrow="Media" title="Asset Library" description="Asset operations restano mock ma tenant-scoped; provider e storage remoto non sono attivi."/><div className="asset-grid">{assets.map((asset)=><Card key={asset.id} className="asset-card"><div className={`asset-preview asset-${asset.previewVariant}`}><span>{asset.name.slice(0,2).toUpperCase()}</span></div><strong>{asset.name}</strong><small>{asset.kind} · {asset.usageCount} utilizzi mock</small><Badge>{asset.tag}</Badge></Card>)}</div></>}

export function StrategyPage(){
  const local=useLocalE2E(); const fallback=useSaasSnapshot(); const [message,setMessage]=useState<string|null>(null); const w=local.workspace;
  if(local.enabled&&w&&local.tenantId){const strategy=w.strategy as any;const generate=async()=>{try{await local.api(`/tenants/${local.tenantId}/strategy`,{method:'POST'});await local.refresh();setMessage('Strategia rigenerata dal Brand Profile e dalla memoria locale.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}};return <><PageHeader eyebrow="Strategia · E2E locale" title="Piano editoriale del brand" description="Derivato da Brand Profile, settore, target, obiettivi, canali, frequenza e memoria editoriale." action={<button data-testid="generate-strategy" className="button" onClick={()=>void generate()}>Rigenera strategia</button>}/>{message&&<Card><p role="status">{message}</p></Card>}{!strategy?<Card><EmptyState title="Strategia non generata" body="Completa onboarding oppure premi Rigenera strategia."/></Card>:<><div className="three-col"><Card><span className="eyebrow">Obiettivi</span><h2>{arrayText(strategy.objectives)}</h2></Card><Card><span className="eyebrow">Audience</span><h2>{arrayText(strategy.audience?.segments)}</h2></Card><Card><span className="eyebrow">Versione / frequenza</span><h2>v{String(strategy.version)} · {String(strategy.scheduling_preferences?.postsPerWeek??3)}/settimana</h2></Card></div><Card><h2>Content pillars</h2><div className="pillar-grid">{w.pillars.map((pillar:any)=><div className="pillar" key={pillar.id}><strong>{pillar.name}</strong><span>{pillar.target_share}%</span><small>{String(pillar.description??'')}</small></div>)}</div></Card><Card><h2>CTA strategy e temi da evitare</h2><p>{arrayText(strategy.platform_strategy?.ctaStrategy)}</p><p className="muted">Evita: {arrayText(strategy.platform_strategy?.avoidThemes)}</p><Link className="button" to="/app/calendar">Genera il calendario →</Link></Card></>}</>}
  return <><PageHeader eyebrow="Strategia" title="Piano editoriale del brand" description="Modalità mock."/><Card><h2>{fallback.usage.weeklyPosts.limit} post / settimana</h2></Card></>;
}

export function ApprovalsPage(){
  const local=useLocalE2E(); const fallback=useSaasSnapshot(); const repository=useSaasRepository(); const [message,setMessage]=useState<string|null>(null);
  if(local.enabled&&local.workspace&&local.tenantId){const pending=local.workspace.posts.flatMap((post:any)=>post.variants.map((variant:any)=>({post,variant}))).filter(({variant}:any)=>variant.platform_decision!=='skip'&&variant.approval_status==='pending');const act=async(kind:'approve'|'reject',variantId:string)=>{try{await local.api(`/tenants/${local.tenantId}/variants/${variantId}/${kind}`,{method:'POST',body:kind==='reject'?JSON.stringify({reason:'Rifiutato da Approval Center'}):undefined});await local.refresh();setMessage(kind==='approve'?'Approvato e inviato allo scheduler quando il post è completo.':'Rifiuto salvato con feedback.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}};return <><PageHeader eyebrow="Controllo umano · database locale" title="Approval Center" description="Preview, copy, data, qualità e differenze utente vengono persistite. AUTO non entra in questa coda."/>{message&&<Card><p role="status">{message}</p></Card>}<Card>{pending.length===0?<EmptyState title="Nessuna approvazione pendente" body="I contenuti AUTO passano direttamente allo scheduling se il quality gate è verde."/>:pending.map(({post,variant}:any)=><article className="approval-row" key={variant.id}><div className="grow"><div className="row-between"><strong>{post.topic}</strong><Badge tone={qualityLabel(post.quality_score)==='Pronto'?'good':'warn'}>{qualityLabel(post.quality_score)}</Badge></div><small>{platformName(variant.platform)} · {new Date(variant.scheduled_at??post.planned_at).toLocaleString('it-IT')}</small><p><strong>{variant.hook}</strong></p><p>{variant.caption}</p><small>{(variant.hashtags??[]).join(' ')}</small><div className="visual-placeholder">{String(variant.visual_brief?.angle??'Visual mock')}</div></div><div className="approval-actions"><Link className="button secondary small" to={`/app/posts/${post.id}`}>Modifica</Link><button data-testid={`reject-${variant.id}`} className="button secondary small" onClick={()=>void act('reject',variant.id)}>Rifiuta</button><button data-testid={`approve-${variant.id}`} className="button small" onClick={()=>void act('approve',variant.id)}>Approva</button></div></article>)}</Card></>}
  const pending=fallback.posts.filter((post)=>['In approvazione','Da rivedere','Draft'].includes(post.state));return <><PageHeader eyebrow="Controllo umano" title="Approvazioni" description="Coda mock."/><Card>{pending.map((post)=><div className="approval-row" key={post.id}><strong>{post.title}</strong><div><button onClick={()=>repository.rejectPost(post.id)}>Rifiuta</button><button onClick={()=>repository.approvePost(post.id)}>Approva</button></div></div>)}</Card></>;
}

export function ConnectionsPage(){const local=useLocalE2E();const fallback=useSaasSnapshot();if(local.enabled&&local.workspace){return <><PageHeader eyebrow="Provider mock" title="Connessioni social" description="Stesso contratto SocialProvider previsto per i provider reali; OAuth non viene avviato."/><div className="connection-grid">{local.workspace.connections.map((connection:any)=><Card key={connection.id}><div className="row-between"><div className="platform-icon">{platformName(connection.platform).slice(0,2).toUpperCase()}</div><Badge tone={connection.connection_status==='connected'?'good':'warn'}>{connection.connection_status}</Badge></div><h2>{platformName(connection.platform)}</h2><p>Approval: <strong>{String(connection.approval_mode).toUpperCase()}</strong></p><small>Health: {connection.connection_status} · mock</small></Card>)}</div></>}return <><PageHeader eyebrow="Provider" title="Connessioni social" description="Mock"/><div className="connection-grid">{fallback.connections.map((c)=><Card key={c.id}><h2>{c.platform}</h2><Badge>{c.status}</Badge></Card>)}</div></>}

export function AnalyticsPage(){
  const local=useLocalE2E();const fallback=useSaasSnapshot();const [message,setMessage]=useState<string|null>(null);
  if(local.enabled&&local.workspace&&local.tenantId){const w=local.workspace;const totals=w.analytics.reduce((acc:any,s:any)=>{for(const [k,v]of Object.entries(s.metrics??{}))if(typeof v==='number')acc[k]=(acc[k]??0)+v;return acc;},{});const performance=buildPerformance(w);const refresh=async()=>{try{await local.api(`/tenants/${local.tenantId}/learning/refresh`,{method:'POST'});await local.refresh();setMessage('Learning aggiornato con evidence gate.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}};return <><PageHeader eyebrow="Performance · MOCK persistito" title="Analytics & Learning" description="Le metriche sono generate dai provider mock ma rispettano il contratto disponibile per ciascun canale." action={<button data-testid="refresh-learning" className="button" onClick={()=>void refresh()}>Aggiorna learning</button>}/>{message&&<Card><p role="status">{message}</p></Card>}<div className="metric-grid"><MetricCard label="Impressions mock" value={formatMetric(totals.impressions??0)} hint={`${w.analytics.length} snapshot`}/><MetricCard label="Reach mock" value={formatMetric(totals.reach??0)} hint="provider contract"/><MetricCard label="Engagements" value={formatMetric(totals.engagements??0)} hint="provider contract"/><MetricCard label="Click mock" value={formatMetric(totals.clicks??0)} hint="solo se disponibile"/></div><div className="two-col"><Card><h2>Performance per piattaforma</h2>{Object.entries(performance.platform).map(([key,value]:any)=><div className="signal-row" key={key}><span>{platformName(key)}</span><strong>{value.engagements} eng. · {value.posts} post</strong></div>)}</Card><Card><h2>Performance per pillar</h2>{Object.entries(performance.pillar).map(([key,value]:any)=><div className="signal-row" key={key}><span>{key}</span><strong>{value.engagements} eng. · {value.posts} post</strong></div>)}</Card></div><div className="two-col"><Card><h2>Top content</h2><p>{performance.top?.topic??'Campione insufficiente'}</p><small>{performance.top?`${performance.top.engagements} engagements`:''}</small></Card><Card><h2>Worst content</h2><p>{performance.worst?.topic??'Campione insufficiente'}</p><small>{performance.worst?`${performance.worst.engagements} engagements`:''}</small></Card></div><Card><h2>Learning loop</h2>{w.insights.map((insight:any)=><div className="list-row" key={insight.id}><Badge tone={Number(insight.confidence)>=.7?'good':'info'}>{Math.round(Number(insight.confidence)*100)}%</Badge><div><strong>{insight.title}</strong><small>{insight.body}</small></div></div>)}{w.insights.length===0&&<p className="muted">Nessuna modifica automatica della strategia: il campione non è ancora sufficiente.</p>}</Card></>}
  return <><PageHeader eyebrow="Performance" title="Analytics" description="Fixture mock"/><MetricCard label="Impression mock" value={formatMetric(fallback.analytics.impressions)} hint="Fixture"/></>;
}

export function SupportPage(){const local=useLocalE2E();const fallback=useSaasSnapshot();const [text,setText]=useState('Quanti post posso pubblicare questa settimana?');const [answer,setAnswer]=useState('');if(local.enabled&&local.tenantId){const ask=async()=>{const result=await local.api<{answer:string}>(`/tenants/${local.tenantId}/chat`,{method:'POST',body:JSON.stringify({message:text})});setAnswer(result.answer)};return <><PageHeader eyebrow="Assistenza" title="Chatbot tenant-aware" description="Usa soltanto knowledge pubblica + contesto del tenant autenticato."/><Card><div className="chat-thread">{answer&&<div className="chat-ai" data-testid="tenant-chat-answer">{answer}</div>}</div><div className="chat-input"><input data-testid="tenant-chat-input" value={text} onChange={(e)=>setText(e.target.value)}/><button data-testid="tenant-chat-send" className="button" onClick={()=>void ask()}>Invia</button></div><p className="muted">Il backend verifica membership prima di caricare qualsiasi contesto tenant.</p></Card></>}return <><PageHeader eyebrow="Assistenza" title="Supporto AI + umano" description="Mock"/><Card>{fallback.usage.weeklyPosts.limit} post/settimana</Card></>}

export function BillingPage(){const local=useLocalE2E();const fallback=useSaasSnapshot();if(local.enabled&&local.workspace){const ai=local.workspace.aiUsage;const cost=ai.reduce((sum:number,event:any)=>sum+Number(event.estimated_cost_microunits??0),0)/1_000_000;const tasks=Object.entries(ai.reduce((acc:any,event:any)=>{acc[event.task]=(acc[event.task]??0)+1;return acc;},{}));return <><PageHeader eyebrow="Entitlements & cost ledger" title="Piano e quote" description="Nessun checkout. Costi teorici solo se una tariffa mock viene configurata via ambiente."/><div className="two-col"><Card><span className="eyebrow">Piano</span><h2>Local Development · €0</h2><Progress label="Post/settimana configurati" value={Number(local.workspace.onboarding?.frequency?.postsPerWeek??3)} max={14}/><Progress label="Pagine scanner" value={Number(local.workspace.onboarding?.scan_summary?.analyzed??0)} max={50}/></Card><Card><span className="eyebrow">AI usage ledger</span><h2>{ai.length} operazioni</h2><p>Costo teorico configurato: €{cost.toFixed(6)}</p>{tasks.map(([task,count])=><div className="signal-row" key={task}><span>{task}</span><strong>{String(count)}</strong></div>)}<p className="muted">Nessun prezzo OpenAI reale è hardcoded.</p></Card></div></>}return <><PageHeader eyebrow="Entitlements" title="Piano e quote" description="Mock"/><Progress label="Post" value={fallback.usage.weeklyPosts.used} max={fallback.usage.weeklyPosts.limit}/></>}

export function SettingsPage(){const local=useLocalE2E();if(local.enabled&&local.workspace)return <><PageHeader eyebrow="Workspace" title="Impostazioni" description="Configurazioni persistite dal tenant locale."/><div className="two-col"><Card><h2>{String(local.workspace.tenant?.name??'Tenant')}</h2><p>Onboarding: {String(local.workspace.tenant?.onboarding_status)}</p></Card><Card><h2>Publishing per canale</h2>{local.workspace.connections.map((c:any)=><div className="toggle-row" key={c.id}><span><strong>{platformName(c.platform)}</strong><small>{String(c.approval_mode).toUpperCase()}</small></span><Badge>{c.connection_status}</Badge></div>)}<p className="muted">Publishing reale sempre disattivato.</p></Card></div></>;return <><PageHeader eyebrow="Workspace" title="Impostazioni" description="Mock"/></>}

export function AdminPage(){const local=useLocalE2E();const [data,setData]=useState<any>(null);const [message,setMessage]=useState<string|null>(null);if(local.enabled){const load=async()=>{try{setData(await local.api('/admin'));setMessage(null)}catch(e){setMessage(e instanceof Error?e.message:String(e))}};const grant=async()=>{try{await local.api('/dev/grant-platform-admin',{method:'POST'});await load()}catch(e){setMessage(e instanceof Error?e.message:String(e))}};return <><PageHeader eyebrow="Platform admin · RBAC locale" title="Console amministrativa" description="L’endpoint rifiuta utenti senza ruolo platform admin." action={<div className="card-actions"><button className="button secondary" onClick={()=>void grant()}>Claim admin locale</button><button className="button" data-testid="load-admin" onClick={()=>void load()}>Carica dati admin</button></div>}/>{message&&<Card><p role="alert">{message}</p></Card>}{data?<><div className="metric-grid"><MetricCard label="Tenant" value={String(data.tenants.length)} hint="database locale"/><MetricCard label="Utenti/membership" value={String(data.members.length)} hint="RBAC"/><MetricCard label="Post" value={String(data.posts.length)} hint="tutti i tenant"/><MetricCard label="Publishing failures" value={String(data.jobs.filter((j:any)=>j.status==='failed').length)} hint="job locali"/></div><div className="two-col"><Card><h2>AI cost ledger</h2><p>{data.aiUsage.length} usage event</p></Card><Card><h2>Social connections</h2><p>{data.connections.length} connessioni mock</p></Card></div></>:<Card><EmptyState title="Dati admin non caricati" body="Il test RBAC verifica prima il rifiuto, poi assegna il ruolo admin soltanto in modalità local E2E."/></Card>}</>}return <><PageHeader eyebrow="Platform admin" title="Console amministrativa" description="Mock"/></>}

function arrayText(value:unknown){return Array.isArray(value)?value.join(', '):String(value??'—')}
function platformName(value:unknown){return value==='google_business_profile'?'Google Business Profile':String(value??'').replace(/^./,(c)=>c.toUpperCase())}
function qualityLabel(q:any){if(!q||Object.keys(q).length===0)return 'Da controllare';return Number(q.brandMatch??0)>=.8&&Number(q.relevance??0)>=.8&&Number(q.factConfidence??0)>=.75&&Number(q.duplicateRisk??1)<.84?'Pronto':'Problema rilevato'}
function buildPerformance(w:any){const publishedById=new Map(w.published.map((p:any)=>[p.id,p]));const variantById=new Map(w.posts.flatMap((p:any)=>p.variants.map((v:any)=>[v.id,{...v,post:p}])));const pillarById=new Map(w.pillars.map((p:any)=>[p.id,p.name]));const rows=w.analytics.map((s:any)=>{const pub:any=publishedById.get(s.published_post_id);const vp:any=pub?variantById.get(pub.post_variant_id):null;return {topic:vp?.post?.topic??'—',platform:s.platform,pillar:pillarById.get(vp?.post?.pillar_id)??'Senza pillar',engagements:Number(s.metrics?.engagements??0)}});const aggregate=(key:'platform'|'pillar')=>rows.reduce((acc:any,row:any)=>{const k=row[key];acc[k]??={posts:0,engagements:0};acc[k].posts+=1;acc[k].engagements+=row.engagements;return acc;},{});const ranked=[...rows].sort((a,b)=>b.engagements-a.engagements);return {platform:aggregate('platform'),pillar:aggregate('pillar'),top:ranked[0],worst:ranked.at(-1)}}
